import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateCardCycleNet, extractCardSuffix, reconcileCardSettlement } from '../src/services/reviewReconciliation.js';
import { normalizeRows } from '../src/services/fileImport.js';
import { calculateSummary } from '../src/services/finance.js';
import { ensureDeferredReviewTask } from '../src/services/taskEngine.js';
import { MockFinanceDataService } from '../src/services/dataService.js';

const card=(id,date,amount,direction,cycle='cycle-a')=>({id,date,amount,direction,statementCycle:cycle,sourceType:'credit_card_import',sourceAccount:'ויזה •••• 2994',cardSuffix:'2994',financialType:direction==='debit'?'expense':'refund'});
const creditHeavy=[card('c1','2026-08-02',500,'credit'),card('c2','2026-08-03',50,'credit'),card('d1','2026-08-04',100,'debit'),card('d2','2026-08-05',50,'debit'),card('d3','2026-08-06',23.72,'debit')];
const bankCredit={id:'bank-credit',date:'2026-08-12',amount:376.28,direction:'credit',description:'זיכוי לכרטיס ויזה 2994',merchant:'זיכוי לכרטיס ויזה 2994',sourceType:'bank_import'};

test('extracts card suffix and nets a credit-heavy synthetic cycle to 376.28',()=>{assert.equal(extractCardSuffix(bankCredit.description),'2994');assert.equal(calculateCardCycleNet(creditHeavy),376.28)});
test('bank credit matching a card cycle becomes a zero-impact settlement',()=>{const result=reconcileCardSettlement(bankCredit,creditHeavy);assert.equal(result.confidence,'high');assert.equal(result.financialType,'credit_card_settlement');assert.equal(result.countInTotals,false);assert.equal(result.matchingRecordIds.length,5)});
test('bank debit matches a monthly net card charge inside the date window',()=>{const items=[card('d1','2026-08-01',400,'debit'),card('c1','2026-08-07',50,'credit')],result=reconcileCardSettlement({...bankCredit,date:'2026-08-15',amount:350,direction:'debit',description:'חיוב כרטיס אשראי ויזה 2994'},items);assert.equal(result.confidence,'high');assert.equal(result.net,-350)});
test('suffix and date window prevent matching the wrong card',()=>{const wrongSuffix=creditHeavy.map(item=>({...item,cardSuffix:'1111',sourceAccount:'ויזה 1111'}));assert.equal(reconcileCardSettlement(bankCredit,wrongSuffix).confidence,'low');const tooOld=creditHeavy.map(item=>({...item,date:'2026-05-01'}));assert.equal(reconcileCardSettlement(bankCredit,tooOld).confidence,'low')});
test('ambiguous cycles and amount mismatch remain in review',()=>{const duplicateCycle=creditHeavy.map(item=>({...item,id:`b-${item.id}`,statementCycle:'cycle-b'}));assert.equal(reconcileCardSettlement(bankCredit,[...creditHeavy,...duplicateCycle]).confidence,'medium');assert.equal(reconcileCardSettlement({...bankCredit,amount:375},creditHeavy).confidence,'low')});
test('normalization auto-reconciles the synthetic 376.28 case before review',()=>{const parsed=normalizeRows([['תאריך','תיאור','סכום'],['12/08/26','זיכוי לכרטיס ויזה 2994','376.28']],{filename:'bank.csv',selectedSource:'bank_import',reconciliationEvidence:{cardTransactions:creditHeavy}}).rows[0];assert.equal(parsed.financialType,'credit_card_settlement');assert.equal(parsed.reviewStatus,'not_required');assert.match(parsed.classificationExplanation,/2994/)});
test('settlement does not change income, expense, or refund totals',()=>{const underlying=[{financialType:'expense',amount:173.72},{financialType:'refund',amount:550}],settlement={financialType:'credit_card_settlement',amount:376.28,direction:'credit'};const summary=calculateSummary([...underlying,settlement]);assert.equal(summary.income,0);assert.equal(summary.expenses,173.72);assert.equal(summary.reimbursements,550);assert.equal(summary.cashInflows,0)});
test('bank settlement arriving first is deferred and later card data resolves it without task or XP duplication',async()=>{const service=new MockFinanceDataService();const deferred={...bankCredit,financialType:'unknown',reviewStatus:'deferred',userId:'demo-member-a'};service.transactions=[deferred];service.tasks=ensureDeferredReviewTask(deferred,[]).tasks;service.xpEvents=[];const first=await service.rerunDeferredItems({cardTransactions:creditHeavy}),second=await service.rerunDeferredItems({cardTransactions:creditHeavy});assert.equal(first.transactions[0].financialType,'credit_card_settlement');assert.equal(first.engagement.tasks[0].status,'completed');assert.equal(second.engagement.tasks.length,1);assert.equal(second.engagement.xpEvents.length,0)});
test('card details arriving first allow immediate settlement reconciliation',()=>{assert.equal(reconcileCardSettlement(bankCredit,creditHeavy).requiresReview,false)});
test('approved settlement keeps an auditable zero-impact canonical relationship',async()=>{const service=new MockFinanceDataService();const row={...bankCredit,valid:true,excluded:false,importStatus:'ready',financialType:'credit_card_settlement',category:'התחשבנות כרטיס אשראי',reviewStatus:'not_required',reconciliationMatchIds:creditHeavy.map(item=>item.id),classificationExplanation:'הותאם להתחשבנות כרטיס ויזה 2994'};const result=await service.approveFileImport({filename:'synthetic.csv',selectedSource:'bank_import',rows:[row]});const transaction=result.transactions.find(item=>item.merchant===bankCredit.merchant),event=result.canonicalEvents.find(item=>item.id===transaction.canonicalEventId);assert.equal(transaction.countInTotals,false);assert.equal(event.countInTotals,false);assert.equal(event.relationship,'credit_card_settlement');assert.deepEqual(event.settlementOfSourceRecordIds,creditHeavy.map(item=>item.id))});
