import test from 'node:test';
import assert from 'node:assert/strict';
import { createClassificationRule, applySavedClassificationRules, upsertClassificationRule, disableClassificationRule, matchClassificationRule, mergeHydratedClassificationRules } from '../src/services/classificationRules.js';
import { normalizeRows, createValidatedImportPreview } from '../src/services/fileImport.js';
import { calculateSummary } from '../src/services/finance.js';
import { renderFileImport } from '../src/views/fileImportView.js';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { analyzeHistoricalRecords, bulkApproveSafeHistoricalRules } from '../src/services/historicalLearning.js';
import { readFileSync } from 'node:fs';

const rule=()=>createClassificationRule({id:'parents-monthly',target:'family_support',category:'עזרה מההורים',description:'תמיכה משפחתית מההורים',counterparty:'הורים',sourceType:'bank_import',direction:'incoming',typicalAmount:1500,amountTolerance:100,frequency:'monthly'});
const rows=(description='תמיכה משפחתית מההורים',amount='1,500')=>[['תאריך','תיאור התנועה','זכות/חובה ₪'],['10/08/26',description,amount]];

test('a confirmed rule is persisted by the data service for a later import session',async()=>{const service=new MockFinanceDataService();service.classificationRules=[];await service.saveClassificationRule(rule());const later=await service.getClassificationRules();assert.equal(later.length,1);assert.equal(normalizeRows(rows(),{filename:'demo.csv',classificationRules:later}).rows[0].financialType,'family_support')});
test('recurring family support around 1500 is high-confidence and not salary',()=>{const result=normalizeRows(rows(),{filename:'demo.csv',classificationRules:[rule()]}).rows[0];assert.equal(result.reviewStatus,'not_required');assert.equal(result.category,'עזרה מההורים');assert.equal(result.classificationConfidence,'high')});
test('amount alone never matches a materially different context',()=>{assert.equal(applySavedClassificationRules({description:'החזר מחנות',merchant:'החזר מחנות',sourceType:'bank_import',direction:'credit',amount:1500},[rule()]),null)});
test('unknown 376.28 credit remains review',()=>{const result=normalizeRows(rows('זיכוי לא מוכר','376.28'),{filename:'demo.csv',classificationRules:[rule()]}).rows[0];assert.equal(result.financialType,'unknown');assert.equal(result.reviewStatus,'required')});
test('user rule is applied before generic heuristics',()=>{const custom=createClassificationRule({target:'family_support',description:'משכורת תמיכה משפחתית',sourceType:'bank_import',direction:'incoming',typicalAmount:1500});const result=normalizeRows(rows('משכורת תמיכה משפחתית'),{filename:'demo.csv',classificationRules:[custom]}).rows[0];assert.equal(result.financialType,'family_support');assert.equal(result.classificationOrigin,'user_rule')});
test('disabling a rule stops automatic classification',()=>{const disabled=disableClassificationRule([rule()],'parents-monthly');assert.equal(applySavedClassificationRules({description:'תמיכה משפחתית מההורים',merchant:'תמיכה משפחתית מההורים',sourceType:'bank_import',direction:'credit',amount:1500},disabled),null)});
test('saving same rule updates instead of duplicating',()=>{const first=rule(),second={...rule(),id:'second',amountTolerance:150};const saved=upsertClassificationRule([first],second);assert.equal(saved.length,1);assert.equal(saved[0].id,'parents-monthly');assert.equal(saved[0].amountTolerance,150)});
test('rule explanation is visible in the automatic import summary',()=>{const parsed=normalizeRows(rows(),{filename:'demo.csv',classificationRules:[rule()]});const preview={...parsed,dateRange:{from:'2026-08-10',to:'2026-08-10'},summary:{totalRows:1,totalDebits:0,totalCredits:1500},rows:parsed.rows.map(row=>({...row,importStatus:'ready'}))};const html=renderFileImport({fileImportPreview:preview,fileImportFilter:'all',showAutomaticImports:true,ingestion:{importRuns:[]}},{header:()=>''});assert.match(html,/סווג אוטומטית לפי כלל ששמרת/)});
test('family support increases cash flow without inflating employment income',()=>{const summary=calculateSummary([{financialType:'income',amount:10000,direction:'credit'},{financialType:'family_support',amount:1500,direction:'credit'},{financialType:'expense',amount:9000,direction:'debit'}]);assert.equal(summary.income,10000);assert.equal(summary.familySupport,1500);assert.equal(summary.surplusBeforeAllocations,2500)});
test('a recurring government allowance can be learned and is not salary',()=>{const allowance=createClassificationRule({target:'government_benefit',description:'קצבת ילדים חודשית',counterparty:'רשות ממשלתית',sourceType:'bank_import',direction:'incoming',typicalAmount:115,amountTolerance:15,frequency:'monthly'});const parsed=normalizeRows(rows('קצבת ילדים חודשית','115'),{filename:'demo.csv',classificationRules:[allowance]}).rows[0];assert.equal(parsed.financialType,'government_benefit');assert.equal(parsed.category,'קצבאות ומענקים');assert.equal(parsed.reviewStatus,'not_required');const summary=calculateSummary([{financialType:'income',amount:10000},{financialType:'government_benefit',amount:115}]);assert.equal(summary.income,10000);assert.equal(summary.governmentBenefits,115);assert.equal(summary.cashInflows,10115)});
test('classification rules persist when a new mock service instance starts',async()=>{const first=new MockFinanceDataService();first.classificationRules=[];await first.saveClassificationRule(rule());const second=new MockFinanceDataService();assert.ok((await second.getClassificationRules()).some(item=>item.target==='family_support'))});
test('a learned bank credit is reused but a generic bank credit is not',()=>{const bankRule=createClassificationRule({target:'bank_credit',description:'תשלום בנקאי על יתרה חיובית',counterparty:'בנק דמו',sourceType:'bank_import',direction:'incoming',typicalAmount:12,amountTolerance:5,frequency:'monthly'});const known=normalizeRows(rows('תשלום בנקאי על יתרה חיובית','12.50'),{filename:'demo.csv',classificationRules:[bankRule]}).rows[0],unknown=normalizeRows(rows('זיכוי בנקאי אחר','12.50'),{filename:'demo.csv',classificationRules:[bankRule]}).rows[0];assert.equal(known.financialType,'bank_credit');assert.equal(known.category,'ריבית וזיכויים מהבנק');assert.equal(unknown.financialType,'unknown')});
test('bank interest credit increases cash flow without changing salary',()=>{const summary=calculateSummary([{financialType:'income',amount:10000},{financialType:'bank_credit',amount:12.5}]);assert.equal(summary.income,10000);assert.equal(summary.bankCredits,12.5);assert.equal(summary.cashInflows,10012.5)});

const historicalRows=(description,target,extra={})=>Array.from({length:3},(_,index)=>({description,userClassification:target,userCategory:extra.category||target,sourceType:'bank_import',sourceAccount:extra.sourceAccount||'',direction:extra.direction||'credit',amount:extra.amount??1500,date:`2026-0${index+1}-10`,sourceFile:'synthetic-history.xlsx'}));
const historicalRules=(description='סיוע משפחתי חודשי')=>bulkApproveSafeHistoricalRules(analyzeHistoricalRecords(historicalRows(description,'family_support',{category:'עזרה מההורים'})));

test('persisted historical HIGH rule hydrates into a new live import session',async()=>{const first=new MockFinanceDataService();first.classificationRules=[];await first.hydrateClassificationRules(historicalRules());const later=new MockFinanceDataService(),rules=await later.getClassificationRules(),file=new File(['תאריך,תיאור התנועה,זכות/חובה ₪\n10/08/26,סיוע משפחתי חודשי,"1,500"'],'synthetic.csv',{type:'text/csv'}),result=await createValidatedImportPreview(file,{classificationRules:rules,logger:()=>{}}),row=result.preview.rows[0];assert.equal(row.financialType,'family_support');assert.equal(row.reviewStatus,'not_required');assert.equal(result.preview.summary.requiresReview,0)});
test('historical family support requires identity and never amount alone',()=>{const [learned]=historicalRules(),amountOnly=matchClassificationRule(learned,{description:'גורם אחר לחלוטין',merchant:'גורם אחר לחלוטין',sourceType:'bank_import',direction:'credit',amount:1500}),strong=matchClassificationRule(learned,{description:'סיוע משפחתי חודשי',merchant:'סיוע משפחתי חודשי',sourceType:'bank_import',direction:'credit',amount:1500});assert.equal(amountOnly.confidence,'none');assert.deepEqual(amountOnly.failedFeatures,['identity_pattern']);assert.equal(strong.confidence,'high')});
test('wrong counterparty does not inherit parental support classification',()=>{const result=normalizeRows(rows('גורם לא קשור','1,500'),{filename:'synthetic.csv',classificationRules:historicalRules()}).rows[0];assert.equal(result.financialType,'unknown');assert.equal(result.reviewStatus,'required')});
test('learned rules run before review-task decisions without creating a task',async()=>{const service=new MockFinanceDataService();service.classificationRules=[];const rules=await service.hydrateClassificationRules(historicalRules()),engagement=await service.getEngagementState(),parsed=normalizeRows(rows('סיוע משפחתי חודשי'),{filename:'synthetic.csv',classificationRules:rules}).rows[0];assert.equal(parsed.classificationOrigin,'historical_bootstrap');assert.equal(parsed.reviewStatus,'not_required');assert.deepEqual((await service.getEngagementState()).tasks,engagement.tasks)});
test('generic hydration and matching also works for a non-parental historical rule',()=>{const expenseRules=bulkApproveSafeHistoricalRules(analyzeHistoricalRecords(historicalRows('סוחר סינתטי חוזר','expense',{direction:'debit',amount:240,category:'בית'}))),hydrated=mergeHydratedClassificationRules([],expenseRules),parsed=normalizeRows([['תאריך','תיאור התנועה','זכות/חובה ₪'],['10/08/26','סוחר סינתטי חוזר','-240']],{filename:'synthetic.csv',classificationRules:hydrated}).rows[0];assert.equal(parsed.financialType,'expense');assert.equal(parsed.category,'בית');assert.equal(parsed.reviewStatus,'not_required')});
test('live app loads bootstrap rules and passes state rules explicitly to Preview',()=>{const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');assert.match(app,/fetch\('\/api\/classification-rules'\)/);assert.match(app,/hydrateClassificationRules\(payload\.rules\)/);assert.match(app,/createValidatedImportPreview\(file,\{[^}]*classificationRules:state\.classificationRules/s)});
