import test from 'node:test';
import assert from 'node:assert/strict';
import { GmailLinkedReceiptFlow, detectLinkedReceiptEmail, extractDocumentUrls, isSafeDocumentUrl } from '../src/services/gmailLinkedReceipt.js';
import { ImportPipeline } from '../src/services/importPipeline.js';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { createImportEnvelope } from '../src/models.js';

const message={id:'gmail-message-synthetic',threadId:'gmail-thread-synthetic',from:'billing@example.test',to:'family@example.test',subject:'הקבלה שלך זמינה',receivedAt:'2026-09-12T08:00:00Z',attachments:[],htmlBody:'<p>לצפייה במסמך</p><a href="https://documents.example.test/receipt/abc.pdf?token=x&amp;view=1">קבלה</a>'};
const documentResponse=({status=200,type='application/pdf',body='%PDF-synthetic',url='https://documents.example.test/receipt/abc.pdf'}={})=>({status,ok:status>=200&&status<300,url,headers:{get:name=>name.toLowerCase()==='content-type'?type:name.toLowerCase()==='content-length'?String(new TextEncoder().encode(body).length):null},arrayBuffer:async()=>new TextEncoder().encode(body).buffer});
const extractor={extract:async()=>({merchant:'ספק מסמכים סינתטי',purchaseDate:'2026-09-10',total:284.5,paymentMethod:'כרטיס',category:'כללי',confidence:.94,items:[]})};
const setup=()=>{const service=new MockFinanceDataService();service.transactions=[{id:'matching-expense',date:'2026-09-10',merchant:'ספק מסמכים סינתטי',amount:284.5,direction:'debit',financialType:'expense',sourceType:'credit_card_import'}];service.receipts=[];return {service,pipeline:new ImportPipeline({extractor,dataService:service})}};

test('receipt email without attachment is detected and body URL is extracted',()=>{const detected=detectLinkedReceiptEmail(message),urls=extractDocumentUrls(message);assert.equal(detected.detected,true);assert.equal(detected.hasAttachment,false);assert.equal(urls[0],'https://documents.example.test/receipt/abc.pdf?token=x&view=1');assert.equal(detectLinkedReceiptEmail({...message,attachments:[{id:'attachment'}]}).detected,false)});

test('document URL safety blocks local private credentialed and non-HTTPS destinations',()=>{assert.equal(isSafeDocumentUrl('https://documents.example.test/receipt.pdf'),true);for(const url of ['http://documents.example.test/receipt.pdf','https://localhost/receipt.pdf','https://192.168.1.4/receipt.pdf','https://user:pass@example.test/receipt.pdf'])assert.equal(isSafeDocumentUrl(url),false)});

test('safe linked document is ingested matched and linked automatically with email metadata',async()=>{const {service,pipeline}=setup(),flow=new GmailLinkedReceiptFlow({importPipeline:pipeline,fetchDocument:async()=>documentResponse()}),result=await flow.process(message,{userId:'demo-member-a',sourceAccount:'gmail-a'});assert.equal(result.status,'linked_automatically');assert.equal(result.saved.linkedTransactionId,'matching-expense');assert.equal(result.saved.sourceMetadata.sourceType,'gmail');assert.equal(result.saved.sourceMetadata.externalSourceId,message.id);assert.equal(result.saved.sourceMetadata.metadata.email.threadId,message.threadId);assert.equal(result.saved.sourceMetadata.metadata.email.documentUrl,result.documentUrl);assert.equal((await service.getReceipts()).length,1)});

test('authentication-required document falls back without invoking extraction',async()=>{let extracted=false;const {service}=setup(),pipeline=new ImportPipeline({extractor:{extract:async()=>{extracted=true}},dataService:service}),flow=new GmailLinkedReceiptFlow({importPipeline:pipeline,fetchDocument:async()=>documentResponse({type:'text/html',body:'<form>login</form>'})}),result=await flow.process(message);assert.equal(result.status,'fallback_required');assert.equal(result.reason,'authentication_required');assert.equal(extracted,false);assert.equal((await service.getReceipts()).length,0)});

test('email metadata and transaction matching happen before asking the user',async()=>{const {service,pipeline}=setup();service.transactions=[];const flow=new GmailLinkedReceiptFlow({importPipeline:pipeline,fetchDocument:async()=>documentResponse()}),result=await flow.process(message);assert.equal(result.status,'review_required');assert.equal(result.prepared.decision,'manual_review');assert.equal(result.prepared.envelope.metadata.email.messageId,message.id);assert.equal((await service.getReceipts()).length,0)});

test('later uploaded copy deduplicates against Gmail receipt without a second expense',async()=>{const {service,pipeline}=setup(),flow=new GmailLinkedReceiptFlow({importPipeline:pipeline,fetchDocument:async()=>documentResponse()});await flow.process(message);const manualEnvelope=createImportEnvelope({sourceType:'uploaded_pdf',payload:{fileName:'copy.pdf'},userId:'demo-member-a',deviceId:'web-demo'}),copy=new File(['different-local-copy'],'copy.pdf',{type:'application/pdf'}),prepared=await pipeline.prepare(manualEnvelope,copy),saved=await pipeline.commit(prepared,'matching-expense');assert.equal((await service.getReceipts()).length,1);assert.equal((await service.getTransactions()).length,1);assert.ok(saved.sourceRepresentations.some(item=>item.sourceType==='uploaded_pdf'))});
