import test from 'node:test';
import assert from 'node:assert/strict';
import { parseMhtReceipt, parsePdfReceiptText, matchHistoricalReceipt, learnHistoricalReceiptKnowledge } from '../src/services/historicalReceiptLearning.js';
import { calculateSummary } from '../src/services/finance.js';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { readFileSync } from 'node:fs';

const transaction=(extra={})=>({id:'tx-1',canonicalEventId:'event-1',date:'2026-08-04',merchant:'סוחר דמו',amount:120,financialType:'expense',ownerId:'demo-member-a',...extra});
const receipt=(extra={})=>({id:'receipt-1',date:'2026-08-04',merchant:'סוחר דמו',total:120,fileType:'mht',sourceType:'email_receipt',...extra});

test('receipt matches a card transaction with multiple strong signals',()=>{const match=matchHistoricalReceipt(receipt({cardSuffix:'1234'}),[transaction({cardSuffix:'1234'})]);assert.equal(match.confidence,'high');assert.equal(match.transactionId,'tx-1');assert.equal(match.countInTotals,false)});
test('merchant alias is learned across receipt and card descriptions when repeated',()=>{const receipts=[receipt({id:'r1',merchant:'סוחר דמו אונליין'}),receipt({id:'r2',merchant:'סוחר דמו אונליין',date:'2026-08-15'})],transactions=[transaction({merchantAliases:['סוחר דמו אונליין']}),transaction({id:'tx-2',canonicalEventId:'event-2',date:'2026-08-15',merchant:'סוחר דמו',merchantAliases:['סוחר דמו אונליין']})],result=learnHistoricalReceiptKnowledge({receipts,transactions});assert.equal(result.merchantAliases[0].active,true);assert.equal(result.merchantAliases[0].evidenceCount,2)});
test('amount alone is insufficient for receipt matching',()=>{assert.equal(matchHistoricalReceipt(receipt({merchant:'שם אחר',date:'2026-08-20'}),[transaction()]).confidence,'low')});
test('ambiguous multiple-match case remains unresolved',()=>{const match=matchHistoricalReceipt(receipt(),[transaction(),transaction({id:'tx-2',canonicalEventId:'event-2'})]);assert.equal(match.confidence,'conflict');assert.equal(match.status,'unresolved')});
test('store refund links to original purchase and is never income',()=>{const refund=transaction({financialType:'refund',originalPurchaseId:'purchase-1'}),result=learnHistoricalReceiptKnowledge({receipts:[receipt()],transactions:[refund]});assert.equal(result.refundLinks[0].originalPurchaseId,'purchase-1');assert.equal(result.refundLinks[0].countAsIncome,false)});
test('MHT extracts merchant date total reference and items from text content',()=>{const parsed=parseMhtReceipt('Content-Type: text/html\n\nMerchant: Demo Shop | Date: 04/08/2026 | Total: ₪120.00 | Order: ABC-123 | Item: Ball ₪120');assert.equal(parsed.valid,true);assert.equal(parsed.merchant,'Demo Shop');assert.equal(parsed.date,'2026-08-04');assert.equal(parsed.total,120);assert.equal(parsed.items.length,1)});
test('PDF extraction remains unresolved when embedded text is insufficient',()=>{const parsed=parsePdfReceiptText('scanned image only',{filename:'scan.pdf'});assert.equal(parsed.parseStatus,'unresolved');assert.equal(parsed.fallback,'embedded_text_only')});
test('MHT safely decodes a base64 text part',()=>{const content='Merchant: Demo Shop | Date: 04/08/2026 | Total: 120.00',encoded=Buffer.from(content).toString('base64'),parsed=parseMhtReceipt(`Content-Type: text/plain; charset=utf-8\nContent-Transfer-Encoding: base64\n\n${encoded}`);assert.equal(parsed.valid,true);assert.equal(parsed.merchant,'Demo Shop')});
test('MHT supports HTML entities, a unique date and a reusable domain merchant hint',()=>{const parsed=parseMhtReceipt('<html><body>סך הכל &#8362; 120.00 בתאריך 04/08/2026</body></html>',{filename:'mail.demo-shop.co.il_history.mht'});assert.equal(parsed.valid,true);assert.equal(parsed.merchant,'demo shop');assert.equal(parsed.date,'2026-08-04');assert.equal(parsed.total,120)});
test('PDF embedded text may use the filename date but never invents a merchant for a generic receipt name',()=>{const parsed=parsePdfReceiptText('סה״כ לתשלום 120.00',{filename:'קבלה 04_08_2026.pdf'});assert.equal(parsed.date,'2026-08-04');assert.equal(parsed.total,120);assert.equal(parsed.merchant,null);assert.equal(parsed.valid,false)});
test('item-level evidence strengthens reusable product families',()=>{const items=[{category:'מוצרי מזון'},{category:'מוצרי מזון'},{category:'מוצרי מזון'},{category:'ניקיון'},{category:'ניקיון'}],result=learnHistoricalReceiptKnowledge({receipts:[receipt({items})],transactions:[transaction()]});assert.deepEqual(result.itemFamilyEvidence.find(x=>x.family==='מוצרי מזון'),{family:'מוצרי מזון',evidenceCount:3,confidence:'high',active:true});assert.equal(result.itemFamilyEvidence.find(x=>x.family==='ניקיון').active,false)});
test('explicit user classification wins over a conflicting receipt heuristic',()=>{const result=learnHistoricalReceiptKnowledge({receipts:[receipt({category:'פנאי'})],transactions:[transaction()],explicitClassifications:[{merchant:'סוחר דמו',category:'בית'}]});assert.equal(result.categoryEvidence[0].category,'בית');assert.equal(result.categoryEvidence[0].conflict,true)});
test('duplicate source representations have zero additional financial impact',()=>{const before=calculateSummary([transaction()]),result=learnHistoricalReceiptKnowledge({receipts:[receipt()],transactions:[transaction()]}),after=calculateSummary([transaction()]);assert.deepEqual(after,before);assert.equal(result.matches[0].match.countInTotals,false)});
test('owner is learned only with strong card/account evidence',()=>{const strong=learnHistoricalReceiptKnowledge({receipts:[receipt({ownerId:'demo-member-a',ownerEvidence:'card_account'})],transactions:[transaction()]}),weak=learnHistoricalReceiptKnowledge({receipts:[receipt({ownerId:'demo-member-a',ownerEvidence:'filename_hint'})],transactions:[transaction()]});assert.equal(strong.ownerEvidence.length,1);assert.equal(weak.ownerEvidence.length,0)});
test('receipt source expectation is activated only after repeated evidence',()=>{const receipts=[receipt({id:'r1'}),receipt({id:'r2',date:'2026-08-15'})],transactions=[transaction(),transaction({id:'tx-2',canonicalEventId:'event-2',date:'2026-08-15'})],result=learnHistoricalReceiptKnowledge({receipts,transactions});assert.equal(result.sourceRelationships[0].active,true);assert.equal(result.sourceRelationships[0].evidenceCount,2)});
test('historical receipt learning has zero effect on totals XP tasks and Madrid',async()=>{const service=new MockFinanceDataService(),transactions=await service.getTransactions(),engagement=await service.getEngagementState(),result=learnHistoricalReceiptKnowledge({receipts:[receipt()],transactions:[transaction()]});assert.deepEqual(await service.getTransactions(),transactions);assert.deepEqual(await service.getEngagementState(),engagement);assert.equal(result.affectsTotals,false);assert.equal(result.createsXP,false);assert.equal(result.createsTasks,false);assert.equal(result.affectsMadrid,false)});
test('only active high-confidence receipt knowledge is persisted',async()=>{const service=new MockFinanceDataService(),beforeTransactions=await service.getTransactions(),beforeEngagement=await service.getEngagementState(),result=learnHistoricalReceiptKnowledge({receipts:[receipt({id:'r1'}),receipt({id:'r2',date:'2026-08-15'})],transactions:[transaction(),transaction({id:'tx-2',canonicalEventId:'event-2',date:'2026-08-15'})]}),saved=await service.saveHistoricalReceiptKnowledge(result);assert.equal(saved.receiptMatchingPatterns.length,1);assert.equal(saved.sourceRelationships.length,1);assert.deepEqual(await service.getTransactions(),beforeTransactions);assert.deepEqual(await service.getEngagementState(),beforeEngagement)});
test('real receipt files remain guarded from Git',()=>{const ignore=readFileSync(new URL('../.gitignore',import.meta.url),'utf8'),source=readFileSync(new URL('../src/services/historicalReceiptLearning.js',import.meta.url),'utf8');assert.match(ignore,/private-data\//);assert.match(ignore,/historical-data\//);assert.doesNotMatch(source,/8221|8230|rami-levy\.co\.il/)});
