import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeHistoricalRecords, approveHistoricalProposal, bulkApproveSafeHistoricalRules } from '../src/services/historicalLearning.js';
import { reconcileIncomeDocument } from '../src/services/documentReconciliation.js';
import { applySavedClassificationRules } from '../src/services/classificationRules.js';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { readFileSync } from 'node:fs';

const row=(description,target,date='2026-01-10',extra={})=>({description,userClassification:target,userCategory:extra.category||target,sourceType:extra.sourceType||'bank_import',sourceAccount:'household-main',direction:extra.direction||'debit',amount:extra.amount||100,date,sourceFile:extra.sourceFile||'history-a.xlsx',...extra});
const repeat=(description,target,count=3,extra={})=>Array.from({length:count},(_,index)=>row(description,target,`2026-0${index+1}-10`,extra));

test('repeated historical classification creates a high-confidence proposal that can be bulk approved',()=>{const result=analyzeHistoricalRecords(repeat('בית עסק אלמוני','expense'));assert.equal(result.summary.high,1);assert.equal(bulkApproveSafeHistoricalRules(result).length,1)});
test('one-off transaction does not create a strong rule',()=>{const result=analyzeHistoricalRecords([row('אירוע חד פעמי','expense')]);assert.equal(result.summary.high,0);assert.equal(result.summary.low,1)});
test('conflicting explicit history creates conflict and cannot auto-approve',()=>{const result=analyzeHistoricalRecords([row('סוחר סותר','expense'),row('סוחר סותר','refund','2026-02-10')]);assert.equal(result.summary.conflicts,1);assert.throws(()=>approveHistoricalProposal(result.proposals[0]),/explicit classification/)});
test('explicit user classification overrides weaker heuristic',()=>{const result=analyzeHistoricalRecords([row('עמלת שירות מיוחדת','family_support'),{description:'עמלת שירות מיוחדת',sourceType:'bank_import',sourceAccount:'household-main',direction:'debit',date:'2026-02-10'}]);assert.equal(result.proposals[0].target,'family_support');assert.notEqual(result.proposals[0].confidence,'conflict')});
test('parental support, child allowance, savings and investments are learned with their meaning',()=>{const records=[...repeat('עזרה מההורים','family_support',3,{direction:'credit',amount:1500,category:'עזרה מההורים'}),...repeat('ביטוח לאומי ילדים','government_benefit',3,{direction:'credit',category:'קצבאות ומענקים'}),...repeat('הוראת קבע חיסכון','savings_transfer',3,{category:'חיסכון'}),...repeat('העברה לבית השקעות','investment_transfer',3,{category:'השקעות'})];const result=analyzeHistoricalRecords(records);assert.deepEqual(new Set(result.proposals.map(p=>p.target)),new Set(['family_support','government_benefit','savings_transfer','investment_transfer']));assert.equal(result.summary.high,4)});
test('card settlement becomes a reconciliation rule and preserves card relationship',()=>{const result=analyzeHistoricalRecords(repeat('חיוב כרטיס 4321','credit_card_settlement',3,{category:'התחשבנות כרטיס אשראי'})),rule=approveHistoricalProposal(result.proposals[0]);assert.equal(result.proposals[0].ruleType,'reconciliation');assert.equal(rule.target,'credit_card_settlement');assert.equal(rule.cardSuffix,'4321')});
test('refund is not learned as income',()=>{const result=analyzeHistoricalRecords(repeat('החזר מחנות','refund',3,{direction:'credit',category:'זיכויים והחזרים'}));assert.equal(result.proposals[0].target,'refund');assert.notEqual(result.proposals[0].target,'income')});
test('merchant with conflicting categories does not auto-rule',()=>{const records=[row('סוחר מגוון','expense','2026-01-01',{category:'בית'}),row('סוחר מגוון','expense','2026-02-01',{category:'פנאי'})];const result=analyzeHistoricalRecords(records);assert.equal(result.summary.conflicts,1);assert.equal(bulkApproveSafeHistoricalRules(result).length,0)});
test('approved historical rule applies to a future synthetic import',()=>{const proposal=analyzeHistoricalRecords(repeat('סוחר חוזר','expense',3,{amount:240,category:'בית'})).proposals[0],rule=approveHistoricalProposal(proposal),match=applySavedClassificationRules({description:'סוחר חוזר',sourceType:'bank_import',sourceAccount:'household-main',direction:'debit',amount:245},[rule]);assert.equal(match?.financialType,'expense');assert.equal(rule.origin,'historical_bootstrap');assert.equal(rule.userApproved,true)});
test('historical learning persists rules but does not affect totals or XP',async()=>{const service=new MockFinanceDataService(),transactionsBefore=await service.getTransactions(),engagementBefore=await service.getEngagementState();const result=await service.analyzeHistoricalRecords(repeat('סוחר בטוח','expense'));await service.bulkApproveHistoricalRules();assert.deepEqual(await service.getTransactions(),transactionsBefore);assert.deepEqual((await service.getEngagementState()).xpEvents,engagementBefore.xpEvents);assert.equal((await service.getClassificationRules()).some(rule=>rule.origin==='historical_bootstrap'),true);assert.equal(result.affectsTotals,false);assert.equal(result.createsXP,false)});
test('amount alone and unknown descriptions are ignored rather than overfit',()=>{const result=analyzeHistoricalRecords([{amount:376.28,direction:'credit',sourceType:'bank_import'}]);assert.equal(result.proposals.length,0);assert.equal(result.ignored.length,1)});
test('HIGH heuristic without repeated explicit user decisions remains inactive',()=>{const records=Array.from({length:3},(_,index)=>({description:'דפוס עמלה סינתטי',financialType:'expense',direction:'debit',sourceType:'bank_import',date:`2026-0${index+1}-10`}));const result=analyzeHistoricalRecords(records);assert.equal(result.proposals[0].confidence,'high');assert.equal(result.proposals[0].explicitUserEvidence,0);assert.equal(bulkApproveSafeHistoricalRules(result).length,0)});
test('matching compensation document and bank credit reconcile to one economic event',()=>{const document={id:'doc-1',sourceName:'משרד תגמולים דמו',netAmount:8200,paymentDate:'2026-07-01',financialType:'income'},bank=[{id:'bank-1',description:'משרד תגמולים דמו תשלום חודשי',amount:8200,date:'2026-07-02',direction:'credit'}],match=reconcileIncomeDocument(document,bank);assert.equal(match.confidence,'high');assert.equal(match.bankRecordCountInTotals,true);assert.equal(match.documentCountInTotals,false);assert.deepEqual(match.linkedSourceRecordIds,['bank-1','doc-1'])});
test('compensation amount alone cannot reconcile without source identity',()=>{const document={id:'doc-1',sourceName:'מקור א',netAmount:8200,paymentDate:'2026-07-01'},bank=[{id:'bank-1',description:'מקור אחר לחלוטין',amount:8200,date:'2026-07-02',direction:'credit'}];assert.equal(reconcileIncomeDocument(document,bank),null)});
test('real historical exports are guarded from accidental Git inclusion',()=>{const ignore=readFileSync(new URL('../.gitignore',import.meta.url),'utf8');assert.match(ignore,/\/\*\.csv/);assert.match(ignore,/historical-data\//)});
