import test from 'node:test';
import assert from 'node:assert/strict';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { createClassificationRule } from '../src/services/classificationRules.js';
import { clearLocalSnapshotsForTests } from '../src/services/localSnapshot.js';

const preview=row=>({filename:'synthetic-bank.csv',selectedSource:'bank_import',rows:[{valid:true,excluded:false,importStatus:'ready',duplicateStatus:'new',reviewSeverity:'non_critical',blocksImport:false,reference:'synthetic-reference',sourceType:'bank_import',...row}]});
const automaticRow={date:'2026-09-03',merchant:'ספק סינתטי בטוח',description:'ספק סינתטי בטוח',amount:81.25,direction:'debit',financialType:'expense',category:'כללי',classificationConfidence:'high',reviewStatus:'not_required',countInTotals:true};

test('live import creates a local pre-import snapshot that can restore app data',async()=>{clearLocalSnapshotsForTests();const service=new MockFinanceDataService(),before=(await service.getTransactions()).length,result=await service.approveFileImport(preview(automaticRow));assert.equal(result.snapshot.reason,'before_import:synthetic-bank.csv');assert.equal((await service.getLocalSnapshots()).length,1);assert.equal((await service.getTransactions()).length,before+1);await service.restoreLocalSnapshot(result.snapshot.id);assert.equal((await service.getTransactions()).length,before)});

test('safe automatic import preserves one source record linked to one canonical event',async()=>{clearLocalSnapshotsForTests();const service=new MockFinanceDataService(),result=await service.approveFileImport(preview(automaticRow)),record=result.sourceRecords.at(-1),event=result.canonicalEvents.find(item=>item.id===record.canonicalEventId);assert.ok(record);assert.ok(event);assert.deepEqual(event.linkedSourceRecordIds,[record.id]);assert.equal(event.countInTotals,true)});

test('non-critical deferred row imports with zero totals impact and one open review task',async()=>{clearLocalSnapshotsForTests();const service=new MockFinanceDataService();service.tasks=[];const row={...automaticRow,date:'2026-09-04',merchant:'זיכוי סינתטי לא פתור',description:'זיכוי סינתטי לא פתור',amount:42.17,direction:'credit',financialType:'unknown',category:null,classificationConfidence:null,reviewStatus:'deferred',reviewReason:'לבדיקה מאוחר יותר',countInTotals:false},result=await service.approveFileImport(preview(row)),transaction=result.transactions.find(item=>item.merchant===row.merchant),tasks=result.engagement.tasks.filter(item=>item.relatedRecordId===transaction.id);assert.equal(transaction.reviewStatus,'deferred');assert.equal(transaction.countInTotals,false);assert.equal(tasks.length,1);assert.equal(tasks[0].xpAwarded,undefined)});

test('critical possible duplicate blocks before snapshot or mutation',async()=>{clearLocalSnapshotsForTests();const service=new MockFinanceDataService(),existing={id:'existing-synthetic',date:'2026-09-03',merchant:'ספק כפול סינתטי',amount:73.4,direction:'debit',financialType:'expense'};service.transactions=[existing];const row={...automaticRow,date:'2026-09-04',merchant:existing.merchant,description:existing.merchant,amount:existing.amount};await assert.rejects(service.approveFileImport(preview(row)),/Critical import integrity issue/);assert.deepEqual(await service.getTransactions(),[existing]);assert.equal((await service.getLocalSnapshots()).length,0)});

test('duplicate rows inside one file cannot create two canonical events',async()=>{clearLocalSnapshotsForTests();const service=new MockFinanceDataService(),first={...automaticRow,date:'2026-09-05',merchant:'כפילות פנימית סינתטית',description:'כפילות פנימית סינתטית'},second={...first,reference:'different-reference'},input=preview(first);input.rows.push({...input.rows[0],...second});await assert.rejects(service.approveFileImport(input),/Critical import integrity issue/);assert.equal(service.canonicalEvents.length,0)});

test('automatic row without explicit HIGH confidence is blocked',async()=>{clearLocalSnapshotsForTests();const service=new MockFinanceDataService(),row={...automaticRow,classificationConfidence:null};await assert.rejects(service.approveFileImport(preview(row)),/requires high confidence/);assert.equal((await service.getLocalSnapshots()).length,0)});

test('import preparation exposes learned rules and reconciliation evidence together',async()=>{const service=new MockFinanceDataService(),rule=createClassificationRule({target:'expense',description:'ספק מוכר סינתטי',sourceType:'bank_import',direction:'outgoing',typicalAmount:64});service.classificationRules=[rule];service.sourceRecords=[{id:'source-evidence'}];service.receipts=[{id:'receipt-evidence'}];service.transactions=[{id:'card-evidence',sourceType:'credit_card_import'}];const context=await service.getImportPreparationContext();assert.equal(context.classificationRules[0].id,rule.id);assert.equal(context.reconciliationEvidence.sourceRecords[0].id,'source-evidence');assert.equal(context.reconciliationEvidence.receipts[0].id,'receipt-evidence');assert.equal(context.reconciliationEvidence.cardTransactions[0].id,'card-evidence')});
