import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createMadridGoal, madridProgress, applyMadridXPEvent, completeMadridChallengeExactlyOnce, MADRID_TARGET_AMOUNT } from '../src/services/madridGoal.js';
import { renderMadrid, renderMadridHomeCard } from '../src/views/madridView.js';
import { completeTaskExactlyOnce } from '../src/services/taskEngine.js';
import { calculateSummary } from '../src/services/finance.js';

const engagement=()=>({madridGoal:createMadridGoal({realSavedAmount:3200,isDemo:true,planningBreakdown:[]}),tasks:[{id:'task-1',type:'missing_receipt',title:'חסרה קבלה',ownerId:'demo-member-a',status:'open',xpReward:20}],xpEvents:[],userScores:[{userId:'demo-member-a',displayName:'רותם',xp:145,activeStreak:3},{userId:'demo-member-b',displayName:'שמואל',xp:120,activeStreak:4}],challenges:[{id:'c1',title:'שבוע בלי קבלות חסרות',description:'בדיקה',type:'task_completion',taskType:'missing_receipt',target:2,rewardXP:25,status:'active'}]});

test('Madrid goal keeps the 15,000 ILS target and labels demo money',()=>{const state={engagement:engagement()},html=renderMadrid(state,{header:(title)=>`<h1>${title}</h1>`});assert.equal(state.engagement.madridGoal.targetAmount,MADRID_TARGET_AMOUNT);assert.match(html,/15,000/);assert.match(html,/נתוני הדגמה/);assert.match(html,/החיסכון האמיתי יחובר בהמשך/)});
test('XP and money are rendered as separate progress systems',()=>{const html=renderMadrid({engagement:engagement()},{header:()=>''});assert.match(html,/3,200/);assert.match(html,/265 Madrid XP/);assert.match(html,/משחק ומשימות · לא כסף/);assert.match(html,/כסף ו־XP נשארים נפרדים/)});
test('XP event updates game progress without changing saved money',()=>{const goal=createMadridGoal({realSavedAmount:3200,xp:100}),updated=applyMadridXPEvent(goal,{amount:20});assert.equal(updated.xp,120);assert.equal(updated.realSavedAmount,3200)});
test('task XP updates Madrid progress through personal scores',()=>{const before=engagement(),result=completeTaskExactlyOnce({taskId:'task-1',tasks:before.tasks,xpEvents:before.xpEvents,userScores:before.userScores}),progress=madridProgress(before.madridGoal,result.userScores);assert.equal(result.userScores[0].xp,165);assert.equal(progress.xp,285);assert.equal(progress.realSavedAmount,3200)});
test('challenge reward is awarded exactly once with no duplicate XP',()=>{const goal=createMadridGoal({realSavedAmount:3200}),challenge={id:'done',status:'completed',rewardXP:40},base={challengeId:'done',challenges:[challenge],xpEvents:[],userScores:[{userId:'demo-member-a',xp:0}],goal};const once=completeMadridChallengeExactlyOnce(base),twice=completeMadridChallengeExactlyOnce({...base,challenges:once.challenges,xpEvents:once.xpEvents,userScores:once.userScores,goal:once.goal});assert.equal(once.xpEvents.length,1);assert.equal(once.userScores[0].xp,40);assert.equal(twice.xpEvents.length,1);assert.equal(twice.xpEvent,null);assert.equal(twice.goal.realSavedAmount,3200)});
test('personal XP and shared financial goal coexist without spending comparisons',()=>{const html=renderMadrid({engagement:engagement()},{header:()=>''});assert.match(html,/רותם/);assert.match(html,/שמואל/);assert.match(html,/הנבחרת שלנו/);assert.doesNotMatch(html,/מי הוציא פחות|מי מרוויח יותר/)});
test('dashboard Madrid card opens the main Madrid destination',()=>{const html=renderMadridHomeCard(engagement());assert.match(html,/data-nav="madridGoal"/);assert.match(html,/הדרך למדריד/)});
test('Madrid is a primary mobile navigation destination',()=>{const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8'),primary=app.match(/const primaryNav=\[(.*?)\];/s)?.[1]||'';assert.match(primary,/madridGoal/);assert.match(primary,/מדריד/)});
test('Madrid demo progress has zero effect on household financial totals',()=>{const transactions=[{financialType:'income',amount:10000},{financialType:'expense',amount:6000}],before=calculateSummary(transactions),goal=applyMadridXPEvent(createMadridGoal({realSavedAmount:3200}),{amount:500}),after=calculateSummary(transactions);assert.deepEqual(after,before);assert.equal(goal.realSavedAmount,3200)});
test('mobile Madrid CSS collapses grids and avoids fixed overflowing widths',()=>{const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/@media\(max-width:800px\).*\.madrid-hero,.madrid-grid\{grid-template-columns:1fr\}/s);assert.doesNotMatch(css,/\.madrid-(?:hero|grid)[^{]*\{[^}]*width:\s*[5-9]\d\dpx/s)});
