import test from 'node:test'; import assert from 'node:assert/strict';
import { groupMicroReceiptRows, groupingSourceHash } from '../src/shared/receiptGrouping.js';
import { dedupeReceiptEnvelopes, matchReceiptEnvelope } from '../src/shared/receiptBridge.js';
import { MemoryReceiptCheckpoint, checkpointStatus } from '../src/shared/receiptCheckpoint.js';
import { normalizeReceiptEnvelope } from '../src/shared/receiptBridge.js';
import { mapSheetRows } from '../backend/receiptBridgeServer.ts';

test('KSP item rows group to one receipt and preserve total',()=>{const rows=[{merchant:'KSP',date:'2026-07-19',invoiceNumber:'749047',name:'a',amount:154},{merchant:'KSP',date:'2026-07-19',invoiceNumber:'749047',name:'b',amount:60},{merchant:'KSP',date:'2026-07-19',invoiceNumber:'749047',name:'c',amount:22}];const [g]=groupMicroReceiptRows(rows);assert.equal(g.items.length,3);assert.equal(g.derivedReceiptTotal,236);const shuffled=[rows[2],rows[0],rows[1]];assert.equal(groupingSourceHash(g),groupingSourceHash(groupMicroReceiptRows(shuffled)[0]));});
test('summary rows excluded and explicit total wins',()=>{const [g]=groupMicroReceiptRows([{sourceImage:'img',merchant:'Max',date:'2026-08-01',name:'item',amount:10},{sourceImage:'img',merchant:'Max',date:'2026-08-01',name:'סה״כ בקבלה',amount:99}]);assert.equal(g.items.length,1);assert.equal(g.derivedReceiptTotal,99);});
test('negative lines are included in safe sum',()=>{const [g]=groupMicroReceiptRows([{sourceImage:'x',merchant:'A',date:'2026-08-01',name:'a',amount:100},{sourceImage:'x',merchant:'A',date:'2026-08-01',name:'b',amount:50},{sourceImage:'x',merchant:'A',date:'2026-08-01',name:'discount',amount:-20}]);assert.equal(g.derivedReceiptTotal,130);});
test('same stable document dedupes, amount alone does not',()=>{const a={externalSourceId:'doc:1',merchant:'A'},b={externalSourceId:'doc:1',merchant:'A'},c={externalSourceId:'doc:2',merchant:'A'};assert.equal(dedupeReceiptEnvelopes([a,b,c]).length,2);assert.equal(dedupeReceiptEnvelopes([{merchant:'A',amount:10},{merchant:'A',amount:10}]).length,2);});
test('checkpoint distinguishes new unchanged and changed',async()=>{const cp=new MemoryReceiptCheckpoint();assert.equal(checkpointStatus(null,'a'),'NEW');await cp.saveCheckpoint([{sourceKey:'x',sourceVersionHash:'a'}]);const saved=await cp.loadCheckpoint();assert.equal(checkpointStatus(saved.x,'a'),'UNCHANGED');assert.equal(checkpointStatus(saved.x,'b'),'SOURCE_CHANGED');});
test('explicit link and unique matcher win; ambiguous remains ambiguous',()=>{const tx=[{id:'t',financialType:'expense',merchant:'Shop',date:'2026-08-01',amount:10}];assert.equal(matchReceiptEnvelope({linkedTransactionId:'t',merchant:'x',amount:1},{transactions:tx}).status,'MATCHED');assert.equal(matchReceiptEnvelope({merchant:'Shop',transactionDate:'2026-08-01',amount:10},{transactions:tx}).status,'MATCHED');const two=[...tx,{id:'t2',financialType:'expense',merchant:'Shop',date:'2026-08-01',amount:10}];assert.equal(matchReceiptEnvelope({merchant:'Shop',transactionDate:'2026-08-01',amount:10},{transactions:two}).status,'AMBIGUOUS');});
test('sheet identity extraction avoids row fallback',()=>{for(const row of [{source:'Gmail – Google Play – msg 1a02e0a0bcbb257b',description:'YouTube Music Premium Family'},{source:'Gmail message 1a05c49d94aa8d04',description:'הזמנה 954346291; חשבונית 758988; קבלה 1698177'},{source:'Gmail – msg 1a043f893f09eadc',merchant:'פנגו'},{sourceImage:'1000323772',merchant:'KSP'}]){const e=normalizeReceiptEnvelope(row,{spreadsheetId:'s',tab:'t',rowNumber:2});assert.equal(e.externalSourceId.includes(':row:'),false)}});
test('runtime-shaped sheet arrays map to stable identities',()=>{const email=mapSheetRows([['תאריך','חודש','ספק/בית עסק','פירוט','קטגוריה','מיקרו-קטגוריה','סכום','מקור','סטטוס התאמה'],['23/07/2026','2026-07','YouTube','YouTube Music','מנוי','','35.90','Gmail – Google Play – msg 1a02e0a0bcbb257b','']], 'קבלות מהמייל');const micro=mapSheetRows([['תאריך','חודש','בית עסק','פריט','קטגוריה ראשית','מיקרו-קטגוריה','סכום','רמת זיהוי','מקור תמונה','','בדיקת קבלה','ערך'],['19/07/2026','2026-07','KSP','item','בית','','10','high','1000323772','','','']], 'קבלות - מיקרו');assert.equal(normalizeReceiptEnvelope(email[0],{spreadsheetId:'s',tab:'קבלות מהמייל'}).externalSourceId.includes(':row:'),false);assert.equal(normalizeReceiptEnvelope(micro[0],{spreadsheetId:'s',tab:'קבלות - מיקרו'}).externalSourceId.includes(':row:'),false)});
test('future explicit identity patterns are stable and provider independent',()=>{const rows=[{source:'Gmail – חשבונית 99999'},{source:'Gmail – חברה כלשהי מס״ד 123456'},{source:'Gmail + הזמנה ABC123'},{source:'Gmail abcdef1234567890'},{description:'פירוט קבלה 98765'},{matchStatus:'סטטוס הזמנה 55555'},{sourceImage:'FUTURE_IMAGE_001'}];for(const row of rows){const a=normalizeReceiptEnvelope(row,{spreadsheetId:'s',tab:'t',rowNumber:2});const b=normalizeReceiptEnvelope(row,{spreadsheetId:'s',tab:'t',rowNumber:99});assert.equal(a.externalSourceId.includes(':row:'),false);assert.equal(a.externalSourceId,b.externalSourceId)}});
test('generic and unlabeled text never fabricate identity',()=>{for(const row of [{source:'Gmail'},{source:'reference 123456789'},{matchStatus:'unrelated status 55555'}]) assert.equal(normalizeReceiptEnvelope(row,{spreadsheetId:'s',tab:'t',rowNumber:2}).identityStrategy,'rowFallback')});
