import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateSummary } from '../src/services/finance.js';
import { buildImportPreview, normalizeRows } from '../src/services/fileImport.js';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { applyConfirmedReimbursement, classifyPsychologicalTreatment, createReimbursementExpectation, matchExpectedReimbursement, PSYCHOLOGICAL_TREATMENT_CATEGORY, REHABILITATION_REIMBURSEMENT_SOURCE } from '../src/services/reimbursementTracking.js';
import { readFileSync } from 'node:fs';

const expense=(id='treatment-a',amount=640,date='2026-09-02')=>({id,date,merchant:'מרכז טיפולי סינתטי',description:'טיפול פסיכולוגי',amount,direction:'debit',financialType:'expense',category:PSYCHOLOGICAL_TREATMENT_CATEGORY});
const credit=(amount=640,date='2026-09-20')=>({id:'rehab-credit',date,merchant:'אגף השיקום',description:'החזר אגף השיקום',amount,direction:'credit',sourceType:'bank_import'});

test('psychological treatment rule is reusable and does not depend on provider or amount',()=>{for(const record of [{description:'טיפול פסיכולוגי',amount:417},{merchant:'מרכז פסיכותרפיה',amount:923},{category:PSYCHOLOGICAL_TREATMENT_CATEGORY,amount:1250}]){const result=classifyPsychologicalTreatment({...record,direction:'debit'});assert.equal(result.category,PSYCHOLOGICAL_TREATMENT_CATEGORY);assert.equal(result.reimbursementExpected,true);assert.equal(result.expectedReimbursementSource,REHABILITATION_REIMBURSEMENT_SOURCE)}});

test('one exact rehabilitation reimbursement matches HIGH while amount difference stays review',()=>{const treatment=expense(),expectation=createReimbursementExpectation(treatment),exact=matchExpectedReimbursement(credit(),[expectation],[treatment]),different=matchExpectedReimbursement(credit(510),[expectation],[treatment]);assert.equal(exact.confidence,'high');assert.equal(exact.expenseTransactionId,treatment.id);assert.equal(different.confidence,'medium');assert.equal(different.requiresReview,true)});

test('multiple eligible treatments remain ambiguous and are never guessed',()=>{const treatments=[expense('treatment-a'),expense('treatment-b')],expectations=treatments.map(item=>createReimbursementExpectation(item)),match=matchExpectedReimbursement(credit(),expectations,treatments);assert.equal(match.confidence,'medium');assert.equal(match.candidateExpectationIds.length,2);assert.match(match.reviewReason,/כמה טיפולים/)});

test('confirmed reimbursement links and offsets net cost without becoming income',()=>{const treatment=expense(),expectation=createReimbursementExpectation(treatment),match=matchExpectedReimbursement(credit(),[expectation],[treatment]),linked=applyConfirmedReimbursement({reimbursement:credit(),match,expectations:[expectation],expenses:[treatment]}),summary=calculateSummary([linked.expenses[0],linked.reimbursement]);assert.equal(linked.reimbursement.financialType,'reimbursement');assert.equal(linked.reimbursement.linkedTransactionId,treatment.id);assert.equal(linked.expectations[0].status,'received');assert.equal(summary.expenses,640);assert.equal(summary.reimbursements,640);assert.equal(summary.netExpenses,0);assert.equal(summary.income,0)});

test('live import creates expectation and later closes it from a matching bank reimbursement',async()=>{const service=new MockFinanceDataService();service.transactions=[];service.tasks=[];service.canonicalEvents=[];service.sourceRecords=[];service.reimbursementExpectations=[];const treatmentParsed=normalizeRows([['תאריך','תיאור','סכום'],['02/09/26','טיפול פסיכולוגי במרכז טיפולי','-640']],{filename:'synthetic-treatment.csv',selectedSource:'bank_import'}),treatmentPreview=buildImportPreview(treatmentParsed);await service.approveFileImport(treatmentPreview);let expectations=await service.getReimbursementExpectations();assert.equal(expectations.length,1);assert.equal(expectations[0].status,'open');const context=await service.getImportPreparationContext(),reimbursementParsed=normalizeRows([['תאריך','תיאור','סכום'],['20/09/26','החזר אגף השיקום','640']],{filename:'synthetic-reimbursement.csv',selectedSource:'bank_import',classificationRules:context.classificationRules,reconciliationEvidence:context.reconciliationEvidence}),reimbursementPreview=buildImportPreview(reimbursementParsed,{existingTransactions:context.existingTransactions,existingReceipts:context.existingReceipts});assert.equal(reimbursementPreview.rows[0].financialType,'reimbursement');assert.equal(reimbursementPreview.rows[0].reviewStatus,'not_required');const result=await service.approveFileImport(reimbursementPreview),treatment=result.transactions.find(item=>item.reimbursementExpected),reimbursement=result.transactions.find(item=>item.financialType==='reimbursement');expectations=await service.getReimbursementExpectations();assert.equal(reimbursement.linkedTransactionId,treatment.id);assert.equal(expectations[0].status,'received');assert.equal(result.engagement.tasks.find(item=>item.type==='reimbursement_followup').status,'completed');assert.equal(result.engagement.tasks.find(item=>item.type==='reimbursement_followup').xpAwarded,false);assert.equal(result.canonicalEvents.find(item=>item.id===reimbursement.canonicalEventId).relationship,'reimbursement')});

test('receipt category creates one reimbursement expectation without duplicate expense',async()=>{const service=new MockFinanceDataService();service.transactions=[];service.receipts=[];service.tasks=[];service.reimbursementExpectations=[];const saved=await service.saveReceipt({merchant:'קליניקה סינתטית',purchaseDate:'2026-09-05',total:530,category:PSYCHOLOGICAL_TREATMENT_CATEGORY,items:[]},null),transactions=await service.getTransactions(),expectations=await service.getReimbursementExpectations();assert.equal(saved.reimbursementExpected,true);assert.equal(transactions.length,1);assert.equal(transactions[0].category,PSYCHOLOGICAL_TREATMENT_CATEGORY);assert.equal(expectations.length,1);assert.equal(expectations[0].receiptId,saved.id)});

test('reimbursement UI exposes gross expected received and net treatment amounts',()=>{const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');for(const label of ['עלות טיפול','החזר צפוי','החזר התקבל','עלות נטו'])assert.match(app,new RegExp(label))});
