import test from 'node:test';
import assert from 'node:assert/strict';
import { reconcileBeforeReview, rerunDeferredReconciliation } from '../src/services/reviewReconciliation.js';
import { applyReviewDecision, normalizeRows, buildImportPreview } from '../src/services/fileImport.js';
import { ensureDeferredReviewTask, closeDeferredReviewTask, batchReviewReminders, completeTaskExactlyOnce, madridGameProgress } from '../src/services/taskEngine.js';
import { MockFinanceDataService } from '../src/services/dataService.js';
import { renderFileImport } from '../src/views/fileImportView.js';

const unknown={id:'unknown-376',date:'2026-08-10',merchant:'זיכוי לא מוכר',description:'זיכוי לא מוכר',amount:376.28,direction:'credit',sourceType:'bank_import',financialType:'unknown',reviewStatus:'deferred'};
const match=(sourceType='credit_card_import',extra={})=>({id:`match-${sourceType}`,date:'2026-08-10',merchant:'זיכוי לא מוכר',amount:376.28,direction:'credit',sourceType,financialType:'reimbursement',category:'החזרים',...extra});

test('cross-source reconciliation and historical classification happen before review',()=>{for(const evidence of [{historicalTransactions:[match('bank_import')]},{sourceRecords:[{...match('credit_card_import'),occurredAt:'2026-08-10',counterparty:'זיכוי לא מוכר'}]}]){const result=reconcileBeforeReview(unknown,evidence);assert.equal(result.confidence,'high');assert.equal(result.financialType,'reimbursement')}});
test('receipt, Gmail and SMS evidence can resolve a deferred transaction',()=>{const cases=[{receipts:[{id:'r',purchaseDate:'2026-08-10',merchant:'זיכוי לא מוכר',total:376.28,category:'קניות'}]},{gmailRecords:[match('gmail')]},{smsRecords:[match('android_sms')]}];for(const evidence of cases)assert.equal(rerunDeferredReconciliation(unknown,evidence).reviewStatus,'resolved_automatically')});
test('bank/card matching stays canonical-ready and Bit/PayBox evidence is supported',()=>{for(const sourceType of ['credit_card_import','bit_wallet','paybox_wallet'])assert.equal(reconcileBeforeReview(unknown,{walletRecords:[match(sourceType)]})?.confidence,'high')});
test('medium confidence is suggested while low confidence remains review',()=>{const medium=reconcileBeforeReview(unknown,{gmailRecords:[match('gmail',{date:'2026-08-12',merchant:'שם אחר'})]});assert.equal(medium.confidence,'medium');assert.equal(medium.requiresReview,true);const low=reconcileBeforeReview(unknown,{gmailRecords:[match('gmail',{date:'2026-08-20'})]});assert.equal(low,null)});
test('defer preserves unknown transaction and is non-blocking',()=>{const deferred=applyReviewDecision({...unknown,reviewStatus:'required',blocksImport:false},'defer');assert.equal(deferred.reviewStatus,'deferred');assert.equal(deferred.financialType,'unknown');assert.equal(deferred.excluded,false);assert.equal(deferred.blocksImport,false)});
test('critical duplicate and parsing integrity failures still block import',()=>{const parsed=normalizeRows([['תאריך','תיאור','סכום'],['10/08/26','ספק דמו','-100'],['לא תאריך','שורה פגומה','-20']],{filename:'demo.csv'});const preview=buildImportPreview(parsed,{existingTransactions:[{id:'old',date:'2026-08-09',merchant:'ספק דמו',amount:100}]});assert.equal(preview.rows[0].blocksImport,true);assert.equal(preview.rows[0].reviewReason,'כפילות אפשרית');assert.equal(preview.rows[1].blocksImport,true)});
test('deferred review task is created exactly once and batching sends one reminder',()=>{const first=ensureDeferredReviewTask(unknown,[],{dueAt:'2026-08-15T08:00:00Z'}),second=ensureDeferredReviewTask(unknown,first.tasks,{dueAt:'2026-08-16T08:00:00Z'});assert.equal(second.tasks.length,1);const batch=batchReviewReminders([...second.tasks,{...second.tasks[0],id:'another',dedupeKey:'other',relatedRecordId:'two'}],new Date('2026-08-17'));assert.equal(batch.taskIds.length,2);assert.match(batch.title,/2 תעלומות/)});
test('automatic resolution closes task without XP or streak penalty',()=>{const task=ensureDeferredReviewTask(unknown,[]).tasks[0],closed=closeDeferredReviewTask(unknown.id,[task]);assert.equal(closed[0].status,'completed');assert.equal(closed[0].xpAwarded,false);const scores=[{userId:'demo-member-a',xp:10,activeStreak:4}];assert.deepEqual(scores,[{userId:'demo-member-a',xp:10,activeStreak:4}])});
test('manual resolution awards XP once and Madrid XP never changes savings',()=>{const task={id:'review-one',type:'transaction_review',ownerId:'u',status:'open',xpReward:10};const first=completeTaskExactlyOnce({taskId:task.id,tasks:[task],xpEvents:[],userScores:[{userId:'u',xp:0}]});const second=completeTaskExactlyOnce({taskId:task.id,tasks:first.tasks,xpEvents:first.xpEvents,userScores:first.userScores});assert.equal(first.userScores[0].xp,10);assert.equal(second.xpEvents.length,1);assert.equal(madridGameProgress(first.xpEvents).financialSavingsImpact,0)});
test('non-critical review no longer disables import, while critical review does',()=>{const base={filename:'demo.csv',selectedSource:'bank_import',error:null,dateRange:{from:'2026-08-10',to:'2026-08-10'},summary:{totalRows:1,totalDebits:0,totalCredits:376.28},rows:[{...unknown,valid:true,excluded:false,importStatus:'ready',reviewStatus:'required',blocksImport:false}]};const state={fileImportPreview:base,fileImportFilter:'all',ingestion:{importRuns:[]}};assert.doesNotMatch(renderFileImport(state,{header:()=>''}),/id="approveImport" disabled/);base.rows[0].blocksImport=true;assert.match(renderFileImport(state,{header:()=>''}),/id="approveImport" disabled/)});
test('service preserves one deferred task and later evidence closes it automatically',async()=>{const service=new MockFinanceDataService();service.tasks=[];service.transactions=[{...unknown}];service.tasks=ensureDeferredReviewTask(unknown,service.tasks).tasks;service.tasks=ensureDeferredReviewTask(unknown,service.tasks).tasks;assert.equal(service.tasks.length,1);const result=await service.rerunDeferredItems({smsRecords:[match('android_sms')]});assert.equal(result.transactions[0].reviewStatus,'resolved_automatically');assert.equal(result.engagement.tasks[0].status,'completed')});
test('exception-first preview hides automatic rows and shows summary counts',()=>{const automatic={valid:true,date:'2026-08-10',description:'הוצאה ברורה',merchant:'הוצאה ברורה',amount:50,direction:'debit',financialType:'expense',category:'כללי',excluded:false,importStatus:'ready',reviewStatus:'not_required',blocksImport:false};const review={...unknown,valid:true,excluded:false,importStatus:'ready',reviewStatus:'required',blocksImport:false};const preview={filename:'demo.csv',selectedSource:'bank_import',dateRange:{from:'2026-08-10',to:'2026-08-10'},summary:{totalRows:2,totalDebits:50,totalCredits:376.28},rows:[automatic,review]};const collapsed=renderFileImport({fileImportPreview:preview,fileImportFilter:'all',showAutomaticImports:false,ingestion:{importRuns:[]}},{header:()=>''});assert.match(collapsed,/1<\/strong><span>עסקאות מוכנות/);assert.match(collapsed,/זיכוי לא מוכר/);assert.doesNotMatch(collapsed,/הוצאה ברורה/);const expanded=renderFileImport({fileImportPreview:preview,fileImportFilter:'all',showAutomaticImports:true,ingestion:{importRuns:[]}},{header:()=>''});assert.match(expanded,/הוצאה ברורה/);assert.match(expanded,/data-import-row="0"/)});
test('known savings and investment transfers are automatic, while critical duplicate is an exception',()=>{const parsed=normalizeRows([['תאריך','תיאור','סכום'],['10/08/26','העברה לחיסכון משפחתי','-1500'],['11/08/26','העברה לחשבון השקעות','-800']],{filename:'demo.csv'});assert.ok(parsed.rows.every(row=>row.reviewStatus==='not_required'));const preview=buildImportPreview(parsed,{existingTransactions:[{id:'old',date:'2026-08-09',merchant:'העברה לחיסכון משפחתי',amount:1500}]});assert.equal(preview.rows[0].blocksImport,true);assert.equal(preview.rows[1].blocksImport,false)});
test('a clearly identified salary is automatic while an unknown credit remains an exception',()=>{const parsed=normalizeRows([['תאריך','תיאור','סכום'],['10/08/26','משכורת חודשית','10000'],['11/08/26','זיכוי לא מוכר','376.28']],{filename:'demo.csv'});assert.equal(parsed.rows[0].financialType,'income');assert.equal(parsed.rows[0].reviewStatus,'not_required');assert.equal(parsed.rows[1].financialType,'unknown');assert.equal(parsed.rows[1].reviewStatus,'required')});
