import test from 'node:test';
import assert from 'node:assert/strict';
import { createBackend } from '../backend/server.ts';
import { createHash } from 'node:crypto';

const key='dGhpcy1pcy1hLTMyLWJ5dGUtZW5jcnlwdGlvbi1rZXk=', salt='s';
const hash=p=>createHash('sha256').update(`${salt}:${p}`).digest('hex');
const config={publicBaseUrl:'http://127.0.0.1',stateEncryptionKey:key,authSigningSecret:key,authSessionDurationMs:600000,authUsers:[{userId:'a',householdId:'h',passwordSalt:salt,passwordHash:hash('a')},{userId:'b',householdId:'h',passwordSalt:salt,passwordHash:hash('b')}]};
async function setup(){const state={version:1,transactions:[{id:'t1',householdId:'h',merchant:'ישן',amount:10,version:1,receiptId:'r1',sourceType:'bank_import'}],receipts:[{id:'r1',householdId:'h',merchant:'חנות',purchaseDate:'2026-08-01',total:10}],idempotency:{}};const repository={async read(){return state},async write(){},async update(fn){return fn(state)}};const server=createBackend({config,financeRepository:repository});await new Promise(r=>server.listen(0,r));const base=`http://127.0.0.1:${server.address().port}`;const login=await (await fetch(`${base}/api/auth/session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:'a',credential:'a'})})).json();return {base,token:login.session,state,server};}
test('authenticated household read, correction conflict, and idempotent cash',async()=>{const x=await setup();try{const h={Authorization:`Bearer ${x.token}`};const state=await (await fetch(`${x.base}/api/finance/state`,{headers:h})).json();assert.equal(state.transactions[0].merchant,'ישן');const edited=await (await fetch(`${x.base}/api/finance/transactions/t1`,{method:'PATCH',headers:{...h,'content-type':'application/json','if-match':'1'},body:JSON.stringify({merchant:'חדש'})})).json();assert.equal(edited.merchant,'חדש');assert.equal((await fetch(`${x.base}/api/finance/transactions/t1`,{method:'PATCH',headers:{...h,'content-type':'application/json','if-match':'1'},body:JSON.stringify({merchant:'stale'})})).status,409);const cash={merchant:'מזומן',amount:25,date:'2026-08-22',category:'בית',subcategory:'קטן'};const first=await (await fetch(`${x.base}/api/finance/cash`,{method:'POST',headers:{...h,'content-type':'application/json','idempotency-key':'cash-1'},body:JSON.stringify(cash)})).json();const second=await (await fetch(`${x.base}/api/finance/cash`,{method:'POST',headers:{...h,'content-type':'application/json','idempotency-key':'cash-1'},body:JSON.stringify(cash)})).json();assert.equal(first.id,second.id);}finally{x.server.close();}});
test('finance read rejects missing session',async()=>{const x=await setup();try{assert.equal((await fetch(`${x.base}/api/finance/state`)).status,401)}finally{x.server.close()}});
test('authenticated import persists real rows and re-import deduplicates',async()=>{const x=await setup();try{const h={Authorization:`Bearer ${x.token}`,'content-type':'application/json'};const row={valid:true,excluded:false,date:'2026-08-20',merchant:'ספק אמיתי לבדיקה',description:'ספק אמיתי לבדיקה',amount:42,direction:'debit',financialType:'expense',category:'בית',subcategory:'תחזוקה',sourceType:'bank_import',externalSourceId:'fixture-1'};const first=await (await fetch(`${x.base}/api/finance/import`,{method:'POST',headers:h,body:JSON.stringify({rows:[row]})})).json();const second=await (await fetch(`${x.base}/api/finance/import`,{method:'POST',headers:h,body:JSON.stringify({rows:[row]})})).json();assert.equal(first.imported,1);assert.equal(second.skipped,1);assert.equal(x.state.transactions.filter(t=>t.externalSourceId==='fixture-1').length,1);assert.equal(x.state.transactions.find(t=>t.externalSourceId==='fixture-1').householdId,'h');}finally{x.server.close()}});
test('shared maintenance tasks and monthly documents are durable and idempotent',async()=>{const x=await setup();x.state.transactions.push({id:'old-expense',householdId:'h',merchant:'ספק ישן',amount:20,date:'2026-07-01',financialType:'expense',receiptId:null});try{const a={Authorization:`Bearer ${x.token}`},first=await (await fetch(`${x.base}/api/finance/state`,{headers:a})).json();assert.ok(first.tasks.some(t=>t.id==='task-missing_receipt:old-expense'));assert.ok(first.expectedDocuments.some(d=>d.documentType==='rehabilitation_document'&&d.dueDate.endsWith('-01')));assert.ok(first.expectedDocuments.some(d=>d.documentType==='credit_card_statement'&&d.dueDate.endsWith('-02')));const completed=await (await fetch(`${x.base}/api/finance/tasks/task-missing_receipt:old-expense/complete`,{method:'POST',headers:a})).json();assert.equal(completed.task.status,'completed');const again=await (await fetch(`${x.base}/api/finance/state`,{headers:a})).json();assert.equal(again.tasks.filter(t=>t.id==='task-missing_receipt:old-expense').length,1);assert.equal(again.rewardEvents['task:task-missing_receipt:old-expense'].amount,10);}finally{x.server.close()}});
