import test from 'node:test'; import assert from 'node:assert/strict';
import { ensureMissingReceiptTask,completeReceiptTask,completeTaskExactlyOnce,remindersFor,challengeProgress,inferTaskOwner } from '../src/services/taskEngine.js';
const tx={id:'t1',date:'2026-08-01',importedAt:'2026-08-01T00:00:00Z',merchant:'מקס סטוק',amount:186,financialType:'expense',receiptId:null,sourceAccount:'כרטיס משפחתי'};
test('missing receipt generates one owned deep-link task after waiting window',()=>{const r=ensureMissingReceiptTask(tx,[],{now:new Date('2026-08-03T00:00:00Z'),waitingPeriodHours:24});assert.equal(r.created.ownerId,'demo-member-a');assert.equal(r.created.deepLink.params.transactionId,'t1')});
test('does not create duplicate missing receipt tasks',()=>{const first=ensureMissingReceiptTask(tx,[],{now:new Date('2026-08-03T00:00:00Z')});const second=ensureMissingReceiptTask(tx,first.tasks,{now:new Date('2026-08-04T00:00:00Z')});assert.equal(second.tasks.length,1);assert.equal(second.created,null)});
test('receipt upload completes its task and creates XP exactly once',()=>{const task={id:'a',type:'missing_receipt',relatedRecordId:'t1',ownerId:'u',status:'open',xpReward:20};const state={tasks:[task],xpEvents:[],userScores:[{userId:'u',xp:0}]};const once=completeReceiptTask('t1',state);assert.equal(once.tasks[0].status,'completed');assert.equal(once.xpEvents.length,1);assert.equal(once.userScores[0].xp,20);const twice=completeTaskExactlyOnce({taskId:'a',tasks:once.tasks,xpEvents:once.xpEvents,userScores:once.userScores});assert.equal(twice.xpEvents.length,1);assert.equal(twice.xpEvent,null)});
test('completed task no longer creates reminders',()=>{const tasks=[{id:'a',type:'missing_receipt',status:'completed',dueAt:'2026-08-01',notificationState:'completed',notificationCount:1}];assert.equal(remindersFor(tasks,{taskType:'missing_receipt',maxNotifications:2},new Date('2026-08-03')).length,0)});
test('challenge progress counts completed tasks in range',()=>{const c=challengeProgress({type:'task_completion',taskType:'missing_receipt',target:2,startDate:'2026-08-01',endDate:'2026-08-31',status:'active'},[{type:'missing_receipt',status:'completed',completedAt:'2026-08-10'}]);assert.equal(c.current,1);assert.equal(c.percent,50)});
test('ownership prefers explicit source user and supports household fallback',()=>{assert.equal(inferTaskOwner({userId:'user-b'}),'user-b');assert.equal(inferTaskOwner({}),null)});
