export class MemoryReceiptCheckpoint { constructor(seed={}){this.map=new Map(Object.entries(seed))} async loadCheckpoint(){return Object.fromEntries(this.map)} async saveCheckpoint(entries){for(const e of entries)this.map.set(e.sourceKey,{sourceKey:e.sourceKey,sourceVersionHash:e.sourceVersionHash,sourceType:e.sourceType,firstSeenAt:e.firstSeenAt,lastSeenAt:e.lastSeenAt,lastProcessedAt:e.lastProcessedAt,lastStatus:e.lastStatus});} }
export function checkpointStatus(previous, sourceVersionHash){if(!previous)return 'NEW'; return previous.sourceVersionHash===sourceVersionHash?'UNCHANGED':'SOURCE_CHANGED'}

export class GcsReceiptCheckpoint {
  constructor({bucket, object, tokenProvider, fetchImpl=fetch}) { this.bucket=bucket; this.object=object; this.tokenProvider=tokenProvider; this.fetchImpl=fetchImpl; }
  async request(method, body) { const token=await this.tokenProvider(); const url=`https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(this.bucket)}/o/${encodeURIComponent(this.object)}`; const r=await this.fetchImpl(url,{method,headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body}); if(r.status===404)return null; if(!r.ok)throw new Error(`checkpoint storage ${r.status}`); return r; }
  async loadCheckpoint(){const r=await this.request('GET'); if(!r)return {}; const meta=await r.json(); const token=await this.tokenProvider(); const media=await this.fetchImpl(`https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(this.bucket)}/o/${encodeURIComponent(this.object)}?alt=media`,{headers:{Authorization:`Bearer ${token}`}}); if(!media.ok)throw new Error(`checkpoint read ${media.status}`); return JSON.parse(await media.text());}
  async saveCheckpoint(entries){const payload=JSON.stringify(Object.fromEntries(entries.map(e=>[e.sourceKey,{sourceKey:e.sourceKey,sourceVersionHash:e.sourceVersionHash,sourceType:e.sourceType,firstSeenAt:e.firstSeenAt,lastSeenAt:e.lastSeenAt,lastProcessedAt:e.lastProcessedAt,lastStatus:e.lastStatus}]))); const token=await this.tokenProvider(); const r=await this.fetchImpl(`https://storage.googleapis.com/upload/storage/v1/b/${encodeURIComponent(this.bucket)}/o?uploadType=media&name=${encodeURIComponent(this.object)}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:payload}); if(!r.ok)throw new Error(`checkpoint write ${r.status}`);}
}
