import { filterPreviewRows } from '../services/fileImport.js';
const money=value=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS'}).format(value||0);
const typeName=type=>({expense:'הוצאה',income:'הכנסה',reimbursement:'החזר',transfer:'העברה פנימית',unknown:'לא מסווג',savings_transfer:'חיסכון',investment_transfer:'השקעה',capital_allocation:'הקצאת הון'}[type]||type);

export function renderFileImport(state,{header}){
  const preview=state.fileImportPreview;if(!preview)return header('ייבוא בנק ואשראי','קובצי CSV או XLSX מעובדים מקומית בלבד')+uploadPanel(state)+history(state);
  const filter=state.fileImportFilter||'all',visibleRows=filterPreviewRows(preview.rows,filter),validRows=preview.rows.filter(row=>row.valid&&!row.excluded),importableRows=validRows.filter(row=>row.importStatus==='ready'),unresolved=validRows.filter(row=>row.reviewStatus==='required'),counts={new:preview.rows.filter(row=>row.importStatus==='ready').length,existing:preview.rows.filter(row=>row.importStatus==='existing').length,review:preview.rows.filter(row=>row.reviewStatus==='required').length,failed:preview.rows.filter(row=>!row.valid).length};
  const canApprove=Boolean(preview.filename)&&validRows.length>0&&importableRows.length>0&&unresolved.length===0&&!preview.error&&preview.selectedSource!=='unknown_financial_export';
  return header('בדיקת ייבוא','בודקים ומחליטים לפני שמוסיפים לנתונים המשפחתיים')+`
    <section class="import-file-head"><div><small>קובץ</small><b>${preview.filename}</b><span>${preview.dateRange.from||'—'} עד ${preview.dateRange.to||'—'}</span></div><label>מקור<select id="importSourceSelect"><option value="bank_import" ${preview.selectedSource==='bank_import'?'selected':''}>חשבון בנק</option><option value="credit_card_import" ${preview.selectedSource==='credit_card_import'?'selected':''}>כרטיס אשראי</option><option value="unknown_financial_export" ${preview.selectedSource==='unknown_financial_export'?'selected':''}>לא ידוע — דורש בחירה</option></select></label><button class="secondary" id="cancelImport">החלפת קובץ</button></section>
    <section class="import-totals"><article><small>שורות שנקראו</small><strong>${preview.summary.totalRows}</strong></article><article><small>חיובים</small><strong>${money(preview.summary.totalDebits)}</strong></article><article><small>זיכויים</small><strong>${money(preview.summary.totalCredits)}</strong></article></section>
    <section class="import-status-filters" aria-label="סינון שורות לפי סטטוס">${[['all','הכול',preview.rows.length],['new','חדשות',counts.new],['existing','קיימות',counts.existing],['review','לבדיקה',counts.review],['failed','לא נקלטו',counts.failed]].map(([value,label,count])=>`<button data-import-filter="${value}" class="${filter===value?'active':''}"><small>${label}</small><strong>${count}</strong></button>`).join('')}</section>
    <div class="import-status-note">סטטוס ייבוא וסטטוס בדיקה מוצגים בנפרד. עסקה חדשה יכולה עדיין לדרוש החלטה לפני הייבוא.</div>
    ${filter!=='all'?`<div class="active-import-filter"><span>מציגים: <b>${filterLabel(filter)}</b> · ${visibleRows.length} שורות</span><button data-import-filter="all">חזרה לכל השורות</button></div>`:''}
    ${preview.selectedSource==='unknown_financial_export'?'<div class="import-warning">לא הצלחנו לזהות בוודאות את המקור. יש לבחור בנק או כרטיס אשראי לפני האישור.</div>':''}
    <section class="import-preview-table"><div class="import-row import-header"><span>לייבא</span><span>תאריך</span><span>תיאור</span><span>סכום</span><span>כיוון</span><span>סוג וקטגוריה</span><span>סטטוס</span></div>${visibleRows.length?visibleRows.map(row=>importRow(row,preview.rows.indexOf(row))).join(''):'<div class="empty-import-filter">אין שורות בסטטוס הזה</div>'}</section>
    <footer class="import-actions"><button class="secondary" id="cancelImport">ביטול</button><div>${unresolved.length?`<small>יש לפתור ${unresolved.length} שורות לפני האישור</small>`:''}<button class="primary" id="approveImport" ${canApprove?'':'disabled'}>אישור וייבוא ${importableRows.length} עסקאות</button></div></footer>${history(state)}`;
}

function uploadPanel(state){const selected=state.fileImportSelection,error=state.fileImportError;return `<section class="file-upload-panel ${error?'has-error':''}"><span>${error?'!':'⇧'}</span><h2>${error?'לא הצלחנו לקרוא את הקובץ':'העלאת קובץ תנועות'}</h2><p>${error?error:'בחרו ייצוא מהבנק או מחברת האשראי. שום מידע לא נשלח לשירות חיצוני.'}</p>${selected?`<div class="selected-file"><b>${selected.name}</b><small>${selected.size?`${Math.ceil(selected.size/1024)} KB`:''}${selected.status==='reading'?' · קוראים את הקובץ…':''}</small></div>`:''}<label class="primary">${error?'נסי לבחור קובץ שוב':'בחירת CSV או XLSX'}<input id="financialFileInputV2" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label><small>עד 15MB · לא יתבצע ייבוא לפני תצוגה מקדימה ואישור</small></section>`}
const filterLabel=value=>({new:'חדשות',existing:'קיימות',review:'דורשות בדיקה',failed:'לא נקלטו'}[value]||'הכול');
function importRow(row,index){const status=row.valid?(row.importStatus==='existing'?'קיימת':'חדשה'):'כשל טכני';return `<article class="import-row ${!row.valid?'malformed':row.importStatus==='existing'?'existing':''} ${row.reviewStatus==='required'?'needs-review':''}"><span class="import-check"><input aria-label="בחירת שורה ${index+1}" type="checkbox" data-import-row="${index}" ${!row.excluded&&row.valid?'checked':''} ${!row.valid?'disabled':''}></span><span class="import-date" data-label="תאריך">${row.date||'—'}</span><span class="import-description" data-label="תיאור"><b>${row.description||'שורה לא תקינה'}</b><small>${row.reference||''}</small></span><span class="import-amount" data-label="סכום">${row.amount?money(row.amount):'—'}</span><span class="import-direction" data-label="כיוון">${row.direction==='debit'?'חיוב':row.direction==='credit'?'זיכוי':'לא ידוע'}</span><span class="import-classification" data-label="סיווג">${typeName(row.financialType)}<small>${row.category||'ללא קטגוריה'}</small></span><span class="row-status ${row.importStatus}">${status}</span>${!row.valid?`<div class="row-failure"><b>${row.parseFailureReason||'השורה לא ניתנת לפענוח'}</b></div>`:row.reviewStatus==='required'?reviewAction(row,index):row.reviewStatus==='resolved'?`<div class="row-resolved">✓ נפתר: ${typeName(row.financialType)}</div>`:''}</article>`}
function reviewAction(row,index){return `<div class="row-review"><div><b>דורש החלטה</b><span>${row.reviewReason||'סיווג לא ודאי'}</span></div><label>איך לסווג?<select data-review-row="${index}"><option value="">בחירת החלטה</option><option value="expense">הוצאה</option><option value="income">הכנסה</option><option value="reimbursement">החזר</option><option value="transfer">העברה פנימית</option><option value="savings_transfer">העברה לחיסכון</option><option value="investment_transfer">העברה להשקעות</option><option value="ignore">התעלם מהשורה</option></select></label></div>`}
function history(state){const runs=state.ingestion.importRuns||[];return `<section class="import-history"><div class="section-title"><div><h2>היסטוריית ייבוא</h2><p>כל ייבוא נשמר לביקורת</p></div></div>${runs.map(run=>`<article><span>${run.status==='success'?'✓':run.status==='partial'?'!':'×'}</span><div><b>${run.filename||'ייבוא הדגמה'}</b><small>${run.source==='bank_import'?'בנק':'כרטיס אשראי'} · ${run.userId||'משתמשת א׳'}</small></div><strong>${run.importedRows??run.recordsSaved??0} נקלטו</strong><small>${run.duplicatesSkipped||0} כפילויות · ${run.rowsRequiringReview||0} לבדיקה · ${run.failedRows||0} נכשלו</small></article>`).join('')}</section>`}
