const money=n=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS'}).format(n||0);
const typeName=type=>({expense:'הוצאה',unknown:'דורש סיווג',savings_transfer:'חיסכון',investment_transfer:'השקעה',capital_allocation:'הקצאת הון'}[type]||type);

export function renderFileImport(state,{header}){
  const preview=state.fileImportPreview;
  if(!preview)return header('ייבוא בנק ואשראי','קובצי CSV או XLSX מעובדים מקומית בלבד')+uploadPanel(state)+history(state);
  const summary=preview.summary;
  const validRows=preview.rows.filter(row=>row.valid&&!row.excluded);
  const importableRows=validRows.filter(row=>row.importStatus==='ready');
  const canApprove=Boolean(preview.filename)&&validRows.length>0&&importableRows.length>0&&!preview.error&&preview.selectedSource!=='unknown_financial_export';
  return header('בדיקת ייבוא','בודקים לפני שמוסיפים לנתונים המשפחתיים')+`
    <section class="import-file-head"><div><small>קובץ</small><b>${preview.filename}</b><span>${preview.dateRange.from||'—'} עד ${preview.dateRange.to||'—'}</span></div><label>מקור<select id="importSourceSelect"><option value="bank_import" ${preview.selectedSource==='bank_import'?'selected':''}>חשבון בנק</option><option value="credit_card_import" ${preview.selectedSource==='credit_card_import'?'selected':''}>כרטיס אשראי</option><option value="unknown_financial_export" ${preview.selectedSource==='unknown_financial_export'?'selected':''}>לא ידוע — דורש בחירה</option></select></label><button class="secondary" id="cancelImport">החלפת קובץ</button></section>
    <section class="import-summary">${[['שורות',summary.totalRows],['חיובים',money(summary.totalDebits)],['זיכויים',money(summary.totalCredits)],['חדשות',summary.newTransactions],['קיימות',summary.existingTransactions],['לבדיקה',summary.requiresReview],['לא נקלטו',summary.malformed]].map(([label,value])=>`<article><small>${label}</small><strong>${value}</strong></article>`).join('')}</section>
    ${preview.selectedSource==='unknown_financial_export'?'<div class="import-warning">לא הצלחנו לזהות בוודאות את המקור. יש לבחור בנק או כרטיס אשראי לפני האישור.</div>':''}
    <section class="import-preview-table"><div class="import-row import-header"><span>לייבא</span><span>תאריך</span><span>תיאור</span><span>סכום</span><span>כיוון</span><span>סוג וקטגוריה</span><span>סטטוס</span></div>${preview.rows.map((row,index)=>importRow(row,index)).join('')}</section>
    <footer class="import-actions"><button class="secondary" id="cancelImport">ביטול</button><button class="primary" id="approveImport" ${canApprove?'':'disabled'}>אישור וייבוא ${importableRows.length} עסקאות</button></footer>${history(state)}`;
}

function uploadPanel(state){const selected=state.fileImportSelection,error=state.fileImportError;return `<section class="file-upload-panel ${error?'has-error':''}"><span>${error?'!':'⇧'}</span><h2>${error?'לא הצלחנו לקרוא את הקובץ':'העלאת קובץ תנועות'}</h2><p>${error?error:'בחרו ייצוא מהבנק או מחברת האשראי. שום מידע לא נשלח לשירות חיצוני.'}</p>${selected?`<div class="selected-file"><b>${selected.name}</b><small>${selected.size?`${Math.ceil(selected.size/1024)} KB`:''}${selected.status==='reading'?' · קוראים את הקובץ…':''}</small></div>`:''}<label class="primary">${error?'נסי לבחור קובץ שוב':'בחירת CSV או XLSX'}<input id="financialFileInputV2" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label><small>עד 15MB · לא יתבצע ייבוא לפני תצוגה מקדימה ואישור</small></section>`}

function importRow(row,index){return `<div class="import-row ${!row.valid?'malformed':row.importStatus==='existing'?'existing':''}"><span><input type="checkbox" data-import-row="${index}" ${!row.excluded&&row.valid?'checked':''} ${!row.valid?'disabled':''}></span><span>${row.date||'—'}</span><span><b>${row.description||'שורה לא תקינה'}</b><small>${row.reference||''}</small></span><span>${row.amount?money(row.amount):'—'}</span><span>${row.direction==='debit'?'חיוב':row.direction==='credit'?'זיכוי':'לא ידוע'}</span><span>${typeName(row.financialType)}<small>${row.category||'ללא קטגוריה'}</small></span><span class="row-status ${row.importStatus}">${row.importStatus==='ready'?'חדשה':row.importStatus==='existing'?'כבר קיימת':'לא נקלטה'}</span></div>`}

function history(state){const runs=state.ingestion.importRuns||[];return `<section class="import-history"><div class="section-title"><div><h2>היסטוריית ייבוא</h2><p>כל ייבוא נשמר לביקורת</p></div></div>${runs.map(run=>`<article><span>${run.status==='success'?'✓':run.status==='partial'?'!':'×'}</span><div><b>${run.filename||'ייבוא הדגמה'}</b><small>${run.source==='bank_import'?'בנק':'כרטיס אשראי'} · ${run.userId||'משתמשת א׳'}</small></div><strong>${run.importedRows??run.recordsSaved??0} נקלטו</strong><small>${run.duplicatesSkipped||0} כפילויות · ${run.rowsRequiringReview||0} לבדיקה · ${run.failedRows||0} נכשלו</small></article>`).join('')}</section>`}
