const confidenceLabel={high:'ביטחון גבוה',medium:'דורש אישור',low:'מידע בלבד',conflict:'נמצאו סיווגים סותרים'};
const targetLabel={expense:'הוצאה',income:'הכנסה',family_support:'עזרה מההורים',government_benefit:'קצבאות ומענקים',bank_credit:'ריבית וזיכויים מהבנק',savings_transfer:'העברה לחיסכון',investment_transfer:'העברה להשקעות',transfer:'העברה פנימית',refund:'החזר / זיכוי',reimbursement:'החזר',credit_card_settlement:'התחשבנות כרטיס אשראי'};

export function renderHistoricalLearning(state,{header}){
  if(state.bootstrapComplete)return `<section class="history-learning-intro bootstrap-complete"><div class="history-shield">✓</div><h1>הלמידה ההיסטורית הושלמה</h1><p>הכללים שאושרו נשמרו. כלי ההקמה מושבת כעת, והאפליקציה הרגילה תשתמש בהם אוטומטית.</p><button class="primary" id="leaveHistoricalBootstrap">חזרה לאפליקציה</button></section>`;
  const result=state.historicalLearning;
  if(!result)return header('למידה מההיסטוריה','מחלצים כללים בלבד — בלי לייבא עסקאות או לשנות סכומים')+`<section class="history-learning-intro"><div class="history-shield">◈</div><h2>מלמדים את האפליקציה פעם אחת</h2><p>אפשר לבחור כמה קובצי CSV או XLSX ישנים. הניתוח מתבצע מקומית, והעסקאות ההיסטוריות לא נכנסות לחשבון.</p><label class="primary historical-file-picker">בחירת קבצים היסטוריים<input id="historicalFiles" type="file" multiple accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label><small>רק הצעות לכללים יישמרו לאחר אישור מפורש</small>${state.historicalLearningError?`<div class="import-warning">${state.historicalLearningError}</div>`:''}</section><section class="history-safety"><article><b>0 שינוי בסכומים</b><span>אין השפעה על totals או שלמות החודש</span></article><article><b>0 נקודות XP</b><span>למידת רקע אינה משימה</span></article><article><b>אישור לפני הפעלה</b><span>רק כללים בטוחים ניתנים לאישור מרוכז</span></article></section>`;
  const visible=result.proposals.filter(item=>state.historicalLearningFilter==='all'||item.confidence===state.historicalLearningFilter);
  return header('למידה מההיסטוריה','הצעות שימושיות בלבד — העסקאות המקוריות נשארות מחוץ לספרים')+`<section class="history-summary"><div><strong>${result.summary.total}</strong><span>כללים אפשריים</span></div><button data-history-filter="high" class="high"><strong>${result.summary.high}</strong><span>בביטחון גבוה</span></button><button data-history-filter="medium"><strong>${result.summary.medium}</strong><span>דורשים אישור</span></button><button data-history-filter="conflict" class="conflict"><strong>${result.summary.conflicts}</strong><span>סותרים</span></button></section><section class="history-safe-action"><div><b>${result.summary.high} כללים בטוחים מוכנים לאישור</b><span>אישור ייצור ClassificationRule רגיל שישמש את הייבוא הבא</span></div><button class="primary" id="approveSafeHistory" ${result.summary.high?'':'disabled'}>אשר את הכללים הבטוחים</button></section><div class="history-filter-bar"><button data-history-filter="all">הצגת כל ההצעות</button><span>${result.summary.recordsAnalyzed} רשומות נותחו · ${result.ignored.length} דפוסים רועשים הושמטו</span></div><section class="history-proposals">${visible.length?visible.map(proposalCard).join(''):'<div class="empty-state"><b>אין הצעות בקבוצה הזאת</b></div>'}</section><section class="history-readonly-note"><b>מצב למידה בלבד</b><span>לא נוצרו עסקאות, totals, משימות קבלה או XP. רק כללים שאושרו נשמרים.</span></section><footer class="bootstrap-finish"><div><b>סיימת לעבור על הכללים?</b><span>לאחר הסיום הכלי יוסתר, והכללים המאושרים ימשיכו לפעול.</span></div><button class="primary" id="finishHistoricalBootstrap">סיום bootstrap</button></footer>`;
}

function proposalCard(item){const candidates=item.candidateClassifications.map(c=>`${targetLabel[c.target]||c.target}${c.category?` / ${c.category}`:''} (${c.occurrences})`).join(' · ');return `<article class="history-proposal ${item.confidence} ${item.status}"><header><span>${confidenceLabel[item.confidence]}</span><em>${item.evidenceCount} מופעים</em></header><div><h2>${targetLabel[item.target]||item.target}</h2><p>${item.category||'ללא קטגוריה'} · ${item.direction==='incoming'?'כסף נכנס':'כסף יוצא'} · ${item.sourceType||'כל מקור'}</p><small>טווח: ${item.dateRange.from||'—'} עד ${item.dateRange.to||'—'} · ${item.sourceFiles.length} קבצים</small>${item.confidence==='conflict'?`<div class="history-conflict">נמצאו סיווגים סותרים: ${candidates}</div>`:''}</div><footer>${item.status==='approved'?'<b class="approved-rule">✓ הכלל אושר</b>':item.status==='rejected'?'<b>ההצעה נדחתה</b>':`<button class="secondary" data-reject-history="${item.id}">דחייה</button>${item.confidence!=='low'&&item.confidence!=='conflict'?`<button class="primary" data-approve-history="${item.id}">אישור הכלל</button>`:''}`}</footer></article>`}
