import { calculateCompleteness } from '../services/completeness.js';
const modeLabels={automatic:'אוטומטי',semi_automatic:'חצי־אוטומטי',manual_reminder:'ידני עם תזכורת'};
const statusLabels={active:'פעיל',connected:'מחובר',waiting_connection:'ממתין לחיבור',manual:'ידני',upload_required:'דורש העלאה',synced:'מסונכרן',up_to_date:'עודכן',missing_data:'חסר מידע',needs_attention:'דורש טיפול',failed:'נכשל',permission_expired:'הרשאה פגה',stale:'לא עודכן לאחרונה',unavailable:'לא זמין לאוטומציה'};

export function renderDataSources(state,{header,date}) {
  const c=calculateCompleteness({month:'2026-08',sources:state.ingestion.sources,expectedDocuments:state.ingestion.expectedDocuments,issues:state.ingestion.issues});
  return header('מקורות מידע','כל ערוצי הקליטה והאם הנתונים הגיעו בזמן')+`<section class="completeness"><div class="completeness-score"><strong>${c.percent}%</strong><span>שלמות נתונים — אוגוסט</span><small>${c.completed} מתוך ${c.total} בדיקות הושלמו</small></div><div class="completeness-checks">${c.checks.map(x=>`<div class="${x.complete?'done':'missing'}"><i>${x.complete?'✓':'!'}</i><span>${x.label}</span><b>${x.complete?'הושלם':'דורש טיפול'}</b></div>`).join('')}</div></section><section class="source-list"><div class="source-list-head"><h2>כל מקורות המידע</h2><span>${state.ingestion.sources.length} מקורות מוגדרים</span></div>${state.ingestion.sources.map(s=>`<article class="source-row"><span class="source-icon">${s.type.includes('gmail')?'✉':s.type.includes('sms')?'▤':s.type.includes('bank')?'₪':s.type.includes('card')?'▱':s.type.includes('camera')?'▧':'◫'}</span><div class="source-name"><b>${s.name}</b><small>${s.owner} · ${s.method}</small></div><span class="mode ${s.mode}">${modeLabels[s.mode]}</span><div class="source-date"><small>ייבוא אחרון</small><b>${s.lastSuccess?date(s.lastSuccess):'טרם חובר'}</b></div><span class="source-status ${s.status}">${statusLabels[s.status]}</span>${s.pendingIssues?`<button data-nav="attention" class="issue-count">${s.pendingIssues} לטיפול</button>`:'<span class="issue-count clear">אין חריגות</span>'}</article>`).join('')}</section><section class="expected-docs"><div class="section-title"><div><h2>מסמכים צפויים</h2><p>מסמכים מחזוריים שאי אפשר תמיד לאסוף אוטומטית</p></div></div>${state.ingestion.expectedDocuments.filter(d=>d.period==='2026-08').map(d=>`<article><span class="doc-state ${d.received?'received':'missing'}">${d.received?'✓':'!'}</span><div><b>${d.documentType} — אוגוסט 2026</b><small>${d.owner} · צפוי עד ${date(d.expectedDate)}</small></div><strong>${d.received?'התקבל':'חסר'}</strong>${d.received?'<span class="completed-label">התזכורת הושלמה</span>':`<label class="upload-doc">העלי עכשיו<input type="file" data-document-upload="${d.id}" accept="image/*,application/pdf"></label>`}</article>`).join('')}</section>`;
}

export function renderAttention(state,{header}) {
  const issues=state.ingestion.issues.filter(i=>i.status==='open');
  return header('דורש טיפול','רק החריגות שצריכות החלטה אנושית')+`<section class="attention-summary"><div><strong>${issues.length}</strong><span>פריטים פתוחים</span></div><p>אין צורך לעבור על כל הנתונים. המערכת מרכזת כאן רק כפילויות, חוסרים ושגיאות.</p></section><section class="issue-list">${issues.length?issues.map(i=>`<article class="issue-card ${i.severity}"><span>${i.type==='suspected_duplicate'?'≋':i.type==='missing_document'?'▧':i.type==='import_failed'?'!':'?'}</span><div><small>${i.type==='suspected_duplicate'?'כפילות אפשרית':i.type==='missing_document'?'מסמך חסר':i.type==='import_failed'?'שגיאת ייבוא':'סיווג חסר'}</small><b>${i.title}</b><p>${i.description}</p></div>${i.expectedDocumentId?`<label class="primary upload-doc">${i.action}<input type="file" data-document-upload="${i.expectedDocumentId}" accept="image/*,application/pdf"></label>`:`<button class="secondary" data-resolve-issue="${i.id}">${i.action}</button>`}</article>`).join(''):'<div class="all-clear"><span>✓</span><h2>הכול מסודר</h2><p>אין כרגע חריגות שמחכות לבדיקה.</p></div>'}</section>`;
}
