import { madridProgress, madridNextBestAction, MADRID_TARGET_AMOUNT } from '../services/madridGoal.js';
import { challengeProgress } from '../services/taskEngine.js';

const money=value=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0}).format(value||0);
const challengeValue=(challenge,state)=>challenge.type==='data_completeness'?challengeProgress(challenge,state.tasks,17):challenge.type==='zero_open_issues'?{...challenge,current:0,percent:0}:challenge.type==='all_tasks'?{...challenge,current:state.tasks.filter(item=>item.status==='completed').length,percent:Math.min(100,Math.round(state.tasks.filter(item=>item.status==='completed').length/challenge.target*100))}:challengeProgress(challenge,state.tasks,0);

export function renderMadrid(state,{header}){
  const engagement=state.engagement,goal=madridProgress(engagement.madridGoal||{targetAmount:MADRID_TARGET_AMOUNT,isDemo:true},engagement.userScores),next=madridNextBestAction(engagement.tasks),milestone=[25,50,75,100].find(value=>goal.moneyPercent<value)||100;
  return header('הדרך למדריד','המשימות הקטנות של היום מקרבות את כל המשפחה ליעד')+`<section class="madrid-hero"><div class="madrid-sky"><div class="madrid-demo">נתוני הדגמה · החיסכון האמיתי יחובר בהמשך</div><div class="madrid-route" aria-label="מסלול ההתקדמות למדריד"><span class="route-airport">🏠</span><i style="--route:${goal.moneyPercent}%"></i><b style="inset-inline-start:${Math.min(92,goal.moneyPercent)}%">✈️</b><span class="route-stadium">🏟️</span></div><div class="madrid-goal-copy"><small>היעד המשפחתי</small><h2>${money(goal.targetAmount)}</h2><p>${money(goal.realSavedAmount)} מתוך ${money(goal.targetAmount)}</p></div><div class="madrid-money-progress"><i style="width:${goal.moneyPercent}%"></i></div><div class="madrid-milestone"><b>${goal.moneyPercent}% מהיעד</b><span>התחנה הבאה: ${milestone}%</span></div></div><div class="madrid-xp-card"><span>${goal.levelIcon}</span><small>משחק ומשימות · לא כסף</small><strong>${goal.xp.toLocaleString('he-IL')} Madrid XP</strong><h3>רמה ${goal.level}: ${goal.levelTitle}</h3>${goal.nextLevel?`<p>עוד ${goal.xpToNext} XP ואתם עולים שלב</p><div><i style="width:${Math.min(100,Math.round(goal.xp/goal.nextLevel.minXP*100))}%"></i></div>`:'<p>הגעתם לרמה הגבוהה ביותר!</p>'}</div></section><section class="madrid-next-action"><span>⚡</span><div><small>המשימה הבאה שלכם</small><h2>${next.title}${next.xp?` · +${next.xp} XP`:''}</h2><p>${next.description}</p></div>${next.taskId?`<button class="madrid-action" data-task-action="${next.taskId}">קדימה, עושים את זה</button>`:'<button class="madrid-action" data-nav="dashboard">חזרה לבית</button>'}</section><div class="madrid-grid"><section class="madrid-challenges"><div class="madrid-section-title"><div><small>משימות קבוצתיות</small><h2>אתגרי מדריד</h2></div><span>בלי לחץ, בלי נקודות שליליות</span></div>${engagement.challenges.map(challenge=>challengeCard(challenge,challengeValue(challenge,engagement))).join('')}</section><section class="madrid-side"><div class="madrid-team"><div class="madrid-section-title"><div><small>משפחת קסהון</small><h2>הנבחרת שלנו</h2></div></div>${engagement.userScores.map((user,index)=>`<article><span>${index===0?'🌿':'⚽'}</span><div><b>${user.displayName}</b><small>${user.activeStreak||0} פעולות ברצף</small></div><strong>${user.xp} XP</strong></article>`).join('')}<p>ההשוואה היא רק על משימות מועילות — אף פעם לא על הוצאות או שכר.</p></div><div class="madrid-budget"><div class="madrid-section-title"><div><small>מודל תכנון עריך</small><h2>מה כולל היעד?</h2></div><span>הדגמה</span></div>${(goal.planningBreakdown||[]).map(item=>`<div><span>${item.name}</span><b>${money(item.amount)}</b></div>`).join('')}<small>החלוקה אינה נתון פיננסי מחייב ותעודכן לפני הזמנה.</small></div></section></div><section class="madrid-integrity"><span>ⓘ</span><div><b>כסף ו־XP נשארים נפרדים</b><p>XP מודד פעולות מועילות באפליקציה. הוא לא הופך לכסף ולא משנה את החיסכון, ההוצאות או התזרים המשפחתי.</p></div></section>`;
}

function challengeCard(challenge,progress){const completed=progress.status==='completed'||progress.current>=progress.target;return `<article class="madrid-challenge ${completed?'complete':''}"><span>${challenge.type==='data_completeness'?'★':challenge.type==='zero_open_issues'?'✓':'⚽'}</span><div><small>+${challenge.rewardXP} XP</small><h3>${challenge.title}</h3><p>${challenge.description||''}</p><div class="challenge-track"><i style="width:${Math.min(100,progress.percent||0)}%"></i></div><b>${progress.current} מתוך ${progress.target}</b></div>${completed&&!challenge.rewardClaimed?`<button data-claim-madrid="${challenge.id}">קבלת הפרס</button>`:completed?'<em>הושלם ✓</em>':''}</article>`}

export function renderMadridHomeCard(engagement){const goal=madridProgress(engagement.madridGoal||{targetAmount:MADRID_TARGET_AMOUNT,isDemo:true},engagement.userScores||[]);return `<button class="madrid-home-card" data-nav="madridGoal"><span class="madrid-home-icon">✈️⚽</span><div><small>הדרך למדריד · נתוני הדגמה</small><b>${goal.moneyPercent}% מהיעד</b><p>${goal.nextLevel?`עוד ${goal.xpToNext} XP לשלב הבא`:'הגעתם לשלב האחרון!'}</p></div><i>‹</i></button>`}
