import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const canonical = new Set([resolve('.local/finance-state.enc'), resolve('.local/gmail-state.enc')]);
const keyBytes = key => { const b = Buffer.from(key, 'base64'); if (b.length !== 32) throw new Error('key must be 32 bytes'); return b; };
export function encryptJson(value, key) { const iv = randomBytes(12), c = createCipheriv('aes-256-gcm', keyBytes(key), iv); const body = Buffer.concat([c.update(JSON.stringify(value)), c.final()]); return Buffer.concat([Buffer.from('FFG1'), iv, c.getAuthTag(), body]); }
export function decryptJson(bytes, key) { if (bytes.subarray(0, 4).toString() !== 'FFG1') throw new Error('invalid format'); const d = createDecipheriv('aes-256-gcm', keyBytes(key), bytes.subarray(4, 16)); d.setAuthTag(bytes.subarray(16, 32)); return JSON.parse(Buffer.concat([d.update(bytes.subarray(32)), d.final()]).toString()); }
const ids = (a, key='id') => new Set((Array.isArray(a)?a:[]).map(x=>String(x?.[key]||'')).filter(Boolean));
export function validateState(kind, s) { if (!s || typeof s !== 'object' || Number(s.version)!==1) throw new Error(`${kind}: invalid schema`); if (kind==='finance' && (!Array.isArray(s.transactions)||!Array.isArray(s.receipts)||!Array.isArray(s.tasks)||!Array.isArray(s.expectedDocuments))) throw new Error('finance: invalid collections'); if (kind==='gmail' && (!s.processedMessages || typeof s.processedMessages!=='object')) throw new Error('gmail: invalid collections'); return true; }
export function compareState(kind, a, b) { validateState(kind,a); validateState(kind,b); const sections=kind==='finance'?['transactions','receipts','tasks','expectedDocuments']:['processedMessages','processedDocuments','processedEvidence','deliveries','staging']; for(const section of sections){const av=kind==='gmail'?Object.keys(a[section]||{}):[...ids(a[section])].sort(); const bv=kind==='gmail'?Object.keys(b[section]||{}):[...ids(b[section])].sort(); if(JSON.stringify(av)!==JSON.stringify(bv)) throw new Error(`${kind}.${section}: identity mismatch`);} if(kind==='finance'){const tx=ids(a.transactions), links=(a.receipts||[]).filter(r=>r.linkedTransactionId&&!tx.has(String(r.linkedTransactionId))); if(links.length) throw new Error('finance: broken receipt link');} return true; }
export function rotateToStaging(kind, source, targetKey, destination) { const out=resolve(destination); if(canonical.has(out)) throw new Error('refusing canonical destination'); if(existsSync(out)) throw new Error('refusing overwrite'); validateState(kind,source); mkdirSync(dirname(out),{recursive:true}); writeFileSync(out, encryptJson(source,targetKey), {mode:0o600,flag:'wx'}); const roundTrip=decryptJson(readFileSync(out),targetKey); compareState(kind,source,roundTrip); return {destination:out}; }
