import { dataService } from './services/dataService.js';
import { calculateSummary, findReceiptMatches } from './services/finance.js';
import { receiptExtractor } from './services/receiptExtraction.js';

const app=document.querySelector('#app');
const money=n=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:2}).format(n);
const date=s=>new Intl.DateTimeFormat('he-IL',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(s));
const icons={dashboard:'⌂',transactions:'↕',receipts:'▧',groceries:'◉',recurring:'↻',reimbursements:'₪',insights:'✦',settings:'⚙'};
const nav=[['dashboard','דשבורד'],['transactions','עסקאות'],['receipts','קבלות'],['groceries','סופר ומוצרים'],['recurring','הוצאות קבועות'],['reimbursements','החזרים'],['insights','תובנות'],['settings','הגדרות']];
const state={page:'dashboard',transactions:[],receipts:[],recurring:[],query:'',filter:'all',modal:false,receiptStep:0,file:null,previewUrl:null,extracted:null,linkedId:null,toast:''};

const typeLabel={expense:'הוצאה',income:'הכנסה',reimbursement:'החזר',transfer:'העברה',refund:'זיכוי'};
function header(title,sub){return `<header class="page-head"><div><p class="eyebrow">אוגוסט 2026</p><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><button class="avatar" aria-label="פרופיל">מש</button></header>`}
function shell(content){return `<aside class="sidebar"><div class="brand"><span class="brandmark">ב</span><div><strong>ביחד</strong><small>הכסף המשפחתי</small></div></div><nav>${nav.map(([id,label])=>`<button data-nav="${id}" class="${state.page===id?'active':''}"><span>${icons[id]}</span>${label}</button>`).join('')}</nav><div class="demo-note"><b>מצב הדגמה</b><span>הנתונים כאן אינם אמיתיים</span></div></aside><main>${content}</main><nav class="bottom-nav" aria-label="ניווט ראשי">${nav.map(([id,label])=>`<button data-nav="${id}" class="${state.page===id?'active':''}"><span>${icons[id]}</span>${label}</button>`).join('')}</nav><button class="fab" id="addReceipt" aria-label="צלמי קבלה"><span>＋</span><b>צלמי קבלה</b></button>${state.modal?receiptModal():''}${state.toast?`<div class="toast">✓ ${state.toast}</div>`:''}`}

function dashboard(){const s=calculateSummary(state.transactions);const cats={};state.transactions.filter(t=>t.financialType==='expense').forEach(t=>cats[t.category]=(cats[t.category]||0)+t.amount);const max=Math.max(...Object.values(cats));return header('שלום, משפחת שמואלי 👋','הנה תמונת המצב של הבית החודש')+`<section class="hero"><div><span>נשאר החודש</span><strong>${money(s.balance)}</strong><small>אחרי הוצאות והחזרים</small></div><div class="hero-ring"><span>72%</span><small>מהיעד</small></div></section><section class="stat-grid"><article><span class="dot income"></span><p>הכנסות</p><strong>${money(s.income)}</strong><small>ללא העברות והחזרים</small></article><article><span class="dot expense"></span><p>הוצאות נטו</p><strong>${money(s.netExpenses)}</strong><small class="good">↓ 8% מחודש שעבר</small></article><article><span class="dot refund"></span><p>החזרים</p><strong>${money(s.reimbursements)}</strong><small>קוזזו מההוצאות</small></article></section><div class="two-col"><section class="card"><div class="section-title"><div><h2>לאן הכסף הלך?</h2><p>לפי קטגוריה, החודש</p></div><button data-nav="insights">לכל התובנות</button></div><div class="bars">${Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([c,v])=>`<div><span>${c}</span><div><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join('')}</div></section><section class="card"><div class="section-title"><div><h2>דורש תשומת לב</h2><p>דברים שכדאי לבדוק</p></div></div><div class="attention"><button data-nav="transactions"><span class="warn">!</span><div><b>3 חיובים ללא קבלה</b><small>אולי יש קבלה שמחכה בטלפון?</small></div><em>‹</em></button><button data-nav="recurring"><span class="up">↗</span><div><b>הכדורגל התייקר ב־12%</b><small>לעומת החיוב הקודם</small></div><em>‹</em></button></div></section></div><section class="card recent"><div class="section-title"><div><h2>עסקאות אחרונות</h2><p>הפעילות האחרונה בבית</p></div><button data-nav="transactions">הצגת הכל</button></div>${transactionRows(state.transactions.slice(0,5))}</section>`}
function transactionRows(rows){return `<div class="transaction-list">${rows.map(t=>`<div class="transaction"><span class="tx-icon ${t.financialType}">${t.financialType==='income'?'↓':t.financialType==='reimbursement'?'↩':'↑'}</span><div class="tx-main"><b>${t.merchant}</b><small>${date(t.date)} · ${t.category}</small></div><div class="tx-amount ${t.direction}"><b>${t.direction==='credit'?'+':'−'}${money(t.amount)}</b><small>${t.receiptId?'▧ קבלה מצורפת':'ללא קבלה'}</small></div></div>`).join('')}</div>`}
function transactionsPage(){let rows=state.transactions.filter(t=>(state.filter==='all'||t.financialType===state.filter)&&(`${t.merchant} ${t.category}`.includes(state.query)));return header('עסקאות','כל התנועות במקום אחד')+`<section class="card"><div class="toolbar"><label class="search">⌕<input id="search" placeholder="חיפוש לפי בית עסק או קטגוריה" value="${state.query}"></label><div class="chips">${[['all','הכל'],['expense','הוצאות'],['income','הכנסות'],['reimbursement','החזרים'],['transfer','העברות']].map(([v,l])=>`<button data-filter="${v}" class="${state.filter===v?'active':''}">${l}</button>`).join('')}</div></div>${transactionRows(rows)}</section>`}
function receiptsPage(){return header('קבלות','המקור נשמר, הנתונים מסודרים')+`<div class="receipt-grid"><button class="upload-card" id="inlineUpload"><span>＋</span><b>הוספת קבלה</b><small>צילום, תמונה או PDF</small></button>${state.receipts.map(r=>`<article class="receipt-card"><div class="paper">${r.fileType==='pdf'?'<b>PDF</b>':'▤'}<span>${r.merchant}</span></div><div><b>${r.merchant}</b><strong>${money(r.total)}</strong></div><small>${date(r.purchaseDate)} · ${r.linkedTransactionId?'מחוברת לעסקה':'לא מחוברת'}</small></article>`).join('')}</div>`}
function groceries(){const items=state.receipts.flatMap(r=>r.items||[]);const cats={};items.forEach(i=>cats[i.category]=(cats[i.category]||0)+i.totalPrice);return header('סופר ומוצרים','מבינים מה נכנס לעגלה, לא רק מה יצא מהחשבון')+`<section class="grocery-hero"><div><small>הוצאות סופר החודש</small><strong>${money(813.70)}</strong><span class="bad">↑ 12% לעומת חודש שעבר</span></div><div><small>סל ממוצע</small><strong>${money(406.85)}</strong><span>2 קניות החודש</span></div></section><div class="two-col"><section class="card"><h2>חלוקה לפי סוג מוצר</h2><div class="donut-wrap"><div class="donut"><span>6<br><small>קטגוריות</small></span></div><div class="legend">${Object.entries(cats).map(([c,v],i)=>`<p><i class="c${i}"></i><span>${c}</span><b>${money(v)}</b></p>`).join('')}</div></div></section><section class="card"><h2>מוצרים שחוזרים</h2>${items.map(i=>`<div class="product"><span>●</span><div><b>${i.rawName}</b><small>${i.category} · ${i.quantity} יח׳</small></div><strong>${money(i.totalPrice)}</strong></div>`).join('')}</section></div><section class="tip"><span>💡</span><div><b>הזדמנות לחיסכון</b><p>הוצאות מוצרי הניקיון גבוהות החודש. קנייה מרוכזת אחת יכולה לעזור.</p></div></section>`}
function recurringPage(){return header('הוצאות קבועות','החיובים שחוזרים בכל חודש')+`<section class="card"><div class="section-title"><h2>צפוי בחודש הבא</h2><strong>${money(state.recurring.reduce((s,x)=>s+x.amount,0))}</strong></div>${state.recurring.map(x=>`<div class="recurring"><span>↻</span><div><b>${x.name}</b><small>החיוב הבא: ${date(x.next)}</small></div>${x.change?`<em>התייקר ${x.change}%</em>`:''}<strong>${money(x.amount)}</strong></div>`).join('')}</section>`}
function reimbursements(){const rows=state.transactions.filter(t=>t.financialType==='reimbursement');return header('החזרים','הוצאות שקיבלתם עליהן כסף בחזרה')+`<section class="reimburse-summary"><span>הוחזר החודש</span><strong>${money(rows.reduce((s,t)=>s+t.amount,0))}</strong><small>החזרים מקטינים את ההוצאה ולא נספרים כהכנסה</small></section><section class="card">${rows.map(t=>`<div class="reimbursement"><span>✓</span><div><b>${t.merchant}</b><small>${t.description} · ${date(t.date)}</small></div><div><strong>${money(t.amount)}</strong><small>קוזז מהוצאות בית</small></div></div>`).join('')}<div class="linked"><b>לאגו שיווק: הוצאה ברוטו ${money(620)}</b><span>החזר מבעלת הדירה ${money(620)}</span><strong>הוצאה נטו ${money(0)}</strong></div></section>`}
function insights(){return header('תובנות','כמה דברים שלמדנו מהחודש שלכם')+`<div class="insight-grid"><article class="insight mint"><span>↘</span><small>מגמה חיובית</small><h2>ההוצאות נטו ירדו ב־8%</h2><p>הוצאתם פחות על בילויים וקניות לבית לעומת יולי.</p></article><article class="insight peach"><span>🛒</span><small>שווה לבדוק</small><h2>הסופר עלה ב־12%</h2><p>עיקר העלייה מגיע ממוצרי ניקיון ומאפים.</p></article><article class="insight lilac"><span>▧</span><small>סדר קטן</small><h2>3 חיובים עדיין בלי קבלה</h2><p>אפשר לצלם ולחבר אותם לעסקה קיימת בלי ליצור כפילות.</p></article><article class="insight blue"><span>◎</span><small>יעד חודשי</small><h2>נשארו 72% מהיעד</h2><p>בקצב הנוכחי אתם בדרך לסיים את החודש בתוך התקציב.</p></article></div>`}
function settings(){return header('הגדרות','העדפות וחיבורי נתונים')+`<section class="card settings"><div><span>₪</span><section><b>מטבע</b><small>מטבע ברירת המחדל</small></section><strong>שקל חדש (ILS)</strong></div><div><span>▣</span><section><b>מקור נתונים</b><small>כרגע האפליקציה משתמשת בנתוני הדגמה</small></section><strong class="pill">מצב דמו</strong></div><div><span>▧</span><section><b>Google Sheets</b><small>השירות מוכן לחיבור בשלב הבא</small></section><button disabled>לא מחובר</button></div><div><span>♙</span><section><b>פרטיות</b><small>אין נתוני חשבון אמיתיים באפליקציה</small></section><strong>מקומי בלבד</strong></div></section>`}
function receiptModal(){const steps=['העלאה','בדיקה','התאמה','שמירה'];let body='';if(state.receiptStep===0)body=`<div class="upload-zone"><span>▧</span><h2>מוסיפים קבלה חדשה</h2><p>אפשר לצלם עכשיו או לבחור קובץ שכבר שמור בטלפון</p><label class="primary camera">📷 צלמי קבלה<input id="cameraInput" type="file" accept="image/*" capture="environment"></label><label class="secondary">▧ בחירת תמונה או PDF<input id="fileInput" type="file" accept="image/*,application/pdf"></label><small>הקובץ המקורי יישמר לצד נתוני הקבלה</small></div>`;
else if(state.receiptStep===1&&!state.extracted)body=`<div class="extracting"><div class="scanner">▤<i></i></div><h2>קוראים את הקבלה…</h2><p>מחלצים בית עסק, תאריך, סכום ומוצרים</p><div class="loading"><i></i></div></div>`;
else if(state.receiptStep===1){const e=state.extracted;body=`<form id="reviewForm"><div class="review-layout"><div class="preview"><div class="mock-receipt">${state.previewUrl?`<img src="${state.previewUrl}" alt="תצוגה מקדימה">`:'<b>PDF</b>'}<span>${e.fileName}</span></div><small>הקובץ המקורי נשמר</small></div><div><div class="success-strip">✓ החילוץ הסתיים · ביטחון ${Math.round(e.confidence*100)}%</div><div class="fields"><label>בית עסק<input name="merchant" value="${e.merchant}" required></label><label>תאריך<input name="purchaseDate" type="date" value="${e.purchaseDate}" required></label><label>סכום כולל<input name="total" type="number" step=".01" value="${e.total}" required></label><label>אמצעי תשלום<input name="paymentMethod" value="${e.paymentMethod}"></label><label>קטגוריה<select name="category"><option>סופר</option><option>בית</option><option>פנאי ובילויים</option><option>איפור וטיפוח</option></select></label></div><div class="items"><div class="section-title"><h3>מוצרים בקבלה</h3><button type="button" id="addItem">＋ הוספת מוצר</button></div>${e.items.map((i,n)=>`<div class="item"><input data-item="name" data-index="${n}" value="${i.rawName}"><input data-item="category" data-index="${n}" value="${i.category}"><input data-item="total" data-index="${n}" type="number" value="${i.totalPrice}"></div>`).join('')}</div></div></div><footer><button type="button" class="secondary" data-back>חזרה</button><button class="primary">המשך לחיפוש התאמה</button></footer></form>`}
else if(state.receiptStep===2){const matches=findReceiptMatches(state.extracted,state.transactions);body=`<div class="match"><span class="match-icon">✓</span><h2>מצאנו עסקה שכנראה מתאימה לקבלה הזו</h2><p>חיבור הקבלה ימנע יצירת הוצאה כפולה</p>${matches.length?matches.map((m,i)=>`<label class="match-card ${state.linkedId===m.id?'selected':''}"><input type="radio" name="match" value="${m.id}" ${state.linkedId===m.id?'checked':''}><span class="score">${Math.round(m.matchScore*100)}%<small>התאמה</small></span><div><b>${m.merchant}</b><small>${date(m.date)} · ${m.source}</small></div><strong>${money(m.amount)}</strong></label>`).join(''):'<div class="empty">לא נמצאה עסקה מתאימה</div>'}<label class="no-match"><input type="radio" name="match" value="" ${!state.linkedId?'checked':''}> זו הוצאה חדשה — אל תחברו לעסקה</label><footer><button class="secondary" data-back>חזרה</button><button class="primary" id="confirmMatch">${state.linkedId?'חיבור ושמירה':'יצירת הוצאה ושמירה'}</button></footer></div>`}
else body=`<div class="saved"><span>✓</span><h2>הקבלה נשמרה!</h2><p>${state.linkedId?'הקבלה חוברה לעסקה הקיימת ולא נוצרה הוצאה כפולה.':'נוצרה עסקה חדשה מהקבלה.'}</p><button class="primary" id="doneReceipt">סיום</button></div>`;
return `<div class="overlay"><section class="modal"><button class="close" id="closeModal">×</button><div class="steps">${steps.map((s,i)=>`<div class="${i<=state.receiptStep?'active':''}"><i>${i<state.receiptStep?'✓':i+1}</i><span>${s}</span></div>`).join('')}</div>${body}</section></div>`}
function render(){const pages={dashboard,transactions:transactionsPage,receipts:receiptsPage,groceries,recurring:recurringPage,reimbursements,insights,settings};app.innerHTML=shell(`<div class="page">${pages[state.page]()}</div>`);bind();}
function openReceipt(){Object.assign(state,{modal:true,receiptStep:0,file:null,previewUrl:null,extracted:null,linkedId:null});render()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.page=b.dataset.nav;render();scrollTo(0,0)});document.querySelector('#addReceipt')?.addEventListener('click',openReceipt);document.querySelector('#inlineUpload')?.addEventListener('click',openReceipt);document.querySelector('#closeModal')?.addEventListener('click',()=>{state.modal=false;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;render();document.querySelector('#search')?.focus()});document.querySelectorAll('#cameraInput,#fileInput').forEach(x=>x.onchange=async e=>{const file=e.target.files[0];if(!file)return;state.file=file;if(file.type.startsWith('image/'))state.previewUrl=URL.createObjectURL(file);state.receiptStep=1;render();state.extracted=await receiptExtractor.extract(file);render()});document.querySelector('[data-back]')?.addEventListener('click',()=>{state.receiptStep--;render()});document.querySelector('#reviewForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(state.extracted,{merchant:f.get('merchant'),purchaseDate:f.get('purchaseDate'),total:Number(f.get('total')),paymentMethod:f.get('paymentMethod'),category:f.get('category')});state.linkedId=findReceiptMatches(state.extracted,state.transactions)[0]?.id||null;state.receiptStep=2;render()});document.querySelector('#addItem')?.addEventListener('click',()=>{state.extracted.items.push({rawName:'מוצר חדש',category:'אחר',totalPrice:0,quantity:1});render()});document.querySelectorAll('[data-item]').forEach(x=>x.onchange=e=>{const i=state.extracted.items[Number(e.target.dataset.index)],k=e.target.dataset.item;i[k==='name'?'rawName':k==='total'?'totalPrice':k]=k==='total'?Number(e.target.value):e.target.value});document.querySelectorAll('[name="match"]').forEach(x=>x.onchange=e=>{state.linkedId=e.target.value||null;render()});document.querySelector('#confirmMatch')?.addEventListener('click',async()=>{await dataService.saveReceipt(state.extracted,state.linkedId);state.transactions=await dataService.getTransactions();state.receipts=await dataService.getReceipts();state.receiptStep=3;render()});document.querySelector('#doneReceipt')?.addEventListener('click',()=>{state.modal=false;state.page='receipts';state.toast='הקבלה נשמרה בהצלחה';render();setTimeout(()=>{state.toast='';render()},2600)})}
async function init(){[state.transactions,state.receipts,state.recurring]=await Promise.all([dataService.getTransactions(),dataService.getReceipts(),dataService.getRecurring()]);render()}
init();
